---
title: "Analise exploratória"
author: "Gutemberg Resende Honorio Filho"
date: "23/02/2021"
output: html_document
---
# Pacotes

```{r}

if(!require(tidyverse)) install.packages("tidyverse")
# para o mapa
if(!require(geobr)) install.packages("geobr")
if(!require(ggspatial)) install.packages("ggspatial")
if(!require(spatstat))  install.packages("spatstat")

# para matrix de correlação
if(!require(PerformanceAnalytics)) install.packages("PerformanceAnalytics")
if(!require(corrplot)) install.packages("corrplot")
if(!require(Hmisc)) install.packages("Hmisc")


# tunel de correlação
if(!require(correlationfunnel)) install.packages("correlationfunnel")

# para  Predictive Power Score (PPS)

# install.packages('devtools')
#devtools :: install_github ('https://github.com/paulvanderlaken/ppsr.git')
library(ppsr)

# PCA

if(!require(FactoMineR)) install.packages("FactoMineR")
if(!require(factoextra)) install.packages("factoextra")

```

# DADOS
```{r Diretório} 

# DIRETÓRIO DOS DADOS 

Tabelabruta<- read.csv("d:/Users/Cristiane Resende/Desktop/Gutemberg Honorio/Mestrado/Repositorio_4\Analise_e_modelagem_Arroz/Merge_1980_2018.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE) # tabela com os dados originais

# criando coluna com macrorregiões

Tabelabruta<- mutate(Tabelabruta,REGIAO = case_when(UF == 'GO'| UF == 'DF' |UF == 'MS' | UF == 'MT' ~ 'Centro_Oeste',
                              UF == 'AL'| UF == 'BA' |UF == 'CE' | UF == 'MA' | UF == 'PB' | UF == 'PE' | UF == 'PI' | UF == 'RN' | UF == 'SE' ~ 'Nordeste',
                              UF == 'AC' | UF == 'AM' | UF == 'AP' | UF == 'PA' | UF == 'RO' | UF == 'RR' | UF == 'TO' ~ 'Norte',
                              UF == 'ES' | UF == 'MG' | UF == 'SP' | UF == 'RJ' ~ 'Sudeste',
                              UF == 'RS' | UF == 'SC' | UF == 'PR' ~ 'Sul'))

# Tabelas acessório

TabelabrutaIRR = subset(Tabelabruta, SIST_CULT == "IRRIGATED") # Somente Irrigado
TabelabrutaTA = subset(Tabelabruta, SIST_CULT == "UPLAND") # Somente Terras altas

# Filtrando os dados


IRR<-TabelabrutaIRR %>% mutate(UR_Media=(umidade_Media),UR_V=	(umidade_V), UR_fld_m=	(umidade_fld_m),	UR_R=	(umidade_R), Graus_dia_ciclo=(graus_dia_ciclo), Graus_dia_FLO=(graus_dia_FLO+graus_dia_IP))

IRR <- select(IRR,latitude, longitude, GENOTIPO, ID_ENSAIO, REGIAO, UF, FLO_E, Tmax_Maxima ,Tmax_fld_m ,	Tmax_R,	Tmax_ACC_R, Tmax_Minima,	Tmax_Media,Tmax_V ,Tmax_ACC_V,	Tmin_Maxima,Tmin_Minima ,	Tmin_Media ,	Tmin_V ,	Tmin_ACC_V , Tmin_fld_m ,	Tmin_R,	Tmin_ACC_R , Chuva_ACC ,	Chuva_ACC_V, Chuva_ACC_R, Rad_ACC_R ,	Rad_ACC ,	Rad_ACC_V, UR_Media, UR_V, UR_fld_m,	UR_R, Graus_dia_ciclo, Graus_dia_FLO)

TA<-TabelabrutaTA %>% mutate(UR_Media=(umidade_Media),UR_V=	(umidade_V), UR_fld_m=	(umidade_fld_m),	UR_R=	(umidade_R), Graus_dia_ciclo=(graus_dia_ciclo), Graus_dia_FLO=(graus_dia_FLO+graus_dia_IP))

TA <- select(TA,latitude, longitude, GENOTIPO, ID_ENSAIO, REGIAO, UF, FLO_E, Tmax_Maxima ,Tmax_fld_m ,	Tmax_R,	Tmax_ACC_R, Tmax_Minima,	Tmax_Media,Tmax_V ,Tmax_ACC_V,	Tmin_Maxima,Tmin_Minima ,	Tmin_Media ,	Tmin_V ,	Tmin_ACC_V , Tmin_fld_m ,	Tmin_R,	Tmin_ACC_R , Chuva_ACC ,	Chuva_ACC_V, Chuva_ACC_R, Rad_ACC_R ,	Rad_ACC ,	Rad_ACC_V, UR_Media, UR_V, UR_fld_m,	UR_R, Graus_dia_ciclo, Graus_dia_FLO)

rm(TabelabrutaIRR,TabelabrutaTA,Tabelabruta)

# Removendo os genótipos que não serão estudados

IRR = IRR[IRR$GENOTIPO %in% c("ALIANCA",	"AVAXI CL",	"BR IRGA 409",	"BR IRGA 410",	"BR IRGA 412",	"BR IRGA 414",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS A704",	"BRS ALVORADA",	"BRS BIGUA",	"BRS CATIANA",	"BRS CIRAD 302",	"BRS FORMOSO",	"BRS FRONTEIRA",	"BRS GUARA",	"BRS JABURU",	"BRS JACANA",	"BRS PAMPA",	"BRS PAMPEIRA",	"BRS PELOTA",	"BRS QUERENCIA",	"BRS SINUELO CL",	"BRS TROPICAL",	"BRSMG RUBELITA",	"CICA 8",	"CT8452",	"DIAMANTE",	"EEA34",	"EMPASC 101",	"EMPASC 102",	"EPAGRI 108",	"EPAGRI 109",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"H6",	"H7 CL",	"IAC1289",	"IAC1298",	"IAC1299",	"IAC1307",	"IAC1311",	"IAPAR 58",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 428",	"IRGA 429",	"IRGA 430",	"IRGA97-05",	"IRGA97-10",	"IRGA97-11",	"IRGA97-28",	"JAVAE",	"JEQUITIBA",	"MARAJO",	"METICA 1",	"MOXOTO",	"OUROMINAS",	"PR267",	"PR268",	"PR306",	"PR331",	"PR349",	"PR380",	"PR498",	"PR631",	"PR67",	"PUITA INTA CL",	"RORAIMA",	"SAO FRANCISCO",	"SC138",	"SC173",	"SC237",	"SC240",	"SC250",	"SCS 112",	"SCS 114 ANDOSAN",	"SCS 116 SATORU",	"SCS 121 CL",	"SCSBRS 111",	"SCSBRS 113 TIO TAKA",	"SCSBRS PIRACEMA",	"SG11551",	"URUCUI"),]
IRR = IRR[IRR$UF!="MT",]

# Filtrando e gerando médias

IRR_Medio<- IRR %>% group_by(ID_ENSAIO, GENOTIPO, REGIAO) %>% summarise(  FLO_M= mean(FLO_E), Tmax_Maxima = mean(Tmax_Maxima) ,Tmax_fld_m = mean(Tmax_fld_m ),	Tmax_R= mean( Tmax_R),	Tmax_ACC_R= mean(Tmax_ACC_R ), Tmax_Minima= mean(Tmax_Minima ),	Tmax_Media= mean( Tmax_Media),Tmax_V = mean(Tmax_V ),Tmax_ACC_V= mean(Tmax_ACC_V ),	Tmin_Maxima= mean(Tmin_Maxima ),Tmin_Minima = mean(Tmin_Minima ),	Tmin_Media = mean(Tmin_Media ),	Tmin_V = mean(Tmin_V ),	Tmin_ACC_V = mean(Tmin_ACC_V ), Tmin_fld_m = mean( Tmin_fld_m),	Tmin_R= mean(Tmin_R ),	Tmin_ACC_R = mean(Tmin_ACC_R ), Chuva_ACC = mean(Chuva_ACC ),	Chuva_ACC_V= mean(Chuva_ACC_V ), Chuva_ACC_R= mean(Chuva_ACC_R ), Rad_ACC_R = mean(Rad_ACC_R ),	Rad_ACC = mean(Rad_ACC ),	Rad_ACC_V= mean(Rad_ACC_V ), UR_Media= mean( UR_Media), UR_V= mean( UR_V), UR_fld_m= mean(UR_fld_m ),	UR_R= mean(UR_R ), Graus_dia_ciclo= mean(Graus_dia_ciclo ), Graus_dia_FLO= mean(Graus_dia_FLO ))

# separando por macrorregião

Centro_oeste<- subset(IRR_Medio, (REGIAO == "Centro_Oeste")) # filtrando por região
Norte<- subset(IRR_Medio, (REGIAO == "Norte")) # filtrando por região
Nordeste<- subset(IRR_Medio, (REGIAO == "Nordeste")) # filtrando por região
Sul<- subset(IRR_Medio, (REGIAO == "Sul")) # filtrando por região
Sudeste<- subset(IRR_Medio, (REGIAO == "Sudeste")) # filtrando por região

```

# Visão geral
## Mapa

```{r , include=F}
Brasil<- read_state(code_state="all",year=2010)

latIRR<- IRR %>%
  group_by(latitude, longitude) %>% 
  count()
names(latIRR) <- c("latitude", "longitude", "Nº_de_ensaios")
  
Mapa<-ggplot(Brasil) +
  geom_sf(aes(group = code_state), data = Brasil, size = 0.1 , fill = "#FFF7C2") +
  geom_point(aes(x = longitude, y = latitude, size = Nº_de_ensaios, colour = "Irrigado"), data = latIRR)+
  scale_colour_manual(values = c("blue"))+
  labs(x = "Longitude", y = "Latitude", title = "   Distribuição geográfica dos ensaios", color = "Legenda") +
  annotation_north_arrow(style=north_arrow_fancy_orienteering)+
  annotation_scale(location="br", height = unit(0.15,"cm"))+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
rm(Brasil, latTA,latIRR)
```
```{r , echo=FALSE, fig.align='center', out.width='100%', fig.asp=0.6, fig.width=9}
Mapa
```
## Ensaios

Número de ensáios realizados por macrorregião.
```{r}

macrorregiao_Ensaios<-apply(with(IRR,table(REGIAO,ID_ENSAIO))>0,1:1,sum)
macrorregiao_Ensaios
```

TOTAL de 238 ensaios realizados


Número de ensáios realizados por estado.
```{r}

Estados_Ensaios<-apply(with(IRR,table(UF,ID_ENSAIO))>0,1:1,sum)
Estados_Ensaios
```
```{r}
barplot(macrorregiao_Ensaios, cex.names =  0.7, main = "Ensaios realizados por macrorregião")
barplot(Estados_Ensaios, cex.names =  0.7, main = "Ensaios realizados por estado")
```
## Genótipos
### Número de genótipos testados por macrorregião.
```{r}

macrorregiao_Genotipo<-apply(with(IRR,table(REGIAO,GENOTIPO))>0,1:1,sum)
macrorregiao_Genotipo
```

TOTAL de 91 genótipos testados

```{r}
ggplot(IRR)+
  geom_point(aes(x = GENOTIPO, y= REGIAO))
barplot(macrorregiao_Genotipo, cex.names =  0.7, main = "Número de genótipos testados por macrorregião")
```

### Número de genótipos testados por estado.
```{r}

Estados_Genotipo<-apply(with(IRR,table(UF,GENOTIPO))>0,1:1,sum)
Estados_Genotipo
```
```{r}
ggplot(IRR)+
  geom_point(aes(x = GENOTIPO, y= UF))
barplot(Estados_Genotipo, cex.names =  0.7, main = "Número de genótipos testados por estado")

```

## Florescimento

```{r}
ggplot(IRR)+
  geom_boxplot(aes(y=FLO_E , x = REGIAO))+
    labs(x = "Macrorregião", y = "Dias após a emergencia (DAE)", title = "Data de florescimento por região")
boxplot(IRR$FLO_E)

```
```{r}
cv<-function(x){coef<-sd(x)/mean(x)*100 
return(coef)}

CV<- IRR %>% group_by(GENOTIPO) %>% summarise(FLO_M = mean(FLO_E), Coef_var = cv(FLO_E))

boxplot(CV$Coef_var, main = "Coeficiente de variação para data de florescimento por genótipo")
```


```{r, message=F}
cv<-function(x){coef<-sd(x)/mean(x)*100 
return(coef)}

CV<- IRR %>% group_by(ID_ENSAIO,REGIAO) %>% summarise(FLO_M = mean(FLO_E), Coef_var = cv(FLO_E))
ggplot(CV)+
  geom_boxplot(aes(y=Coef_var , x = REGIAO))+
    labs(x = "Macrorregião", y = "CV", title = "Coeficiente de variação para data de florescimento por ensaio")

CV<- IRR %>% group_by(GENOTIPO,REGIAO) %>% summarise(FLO_M = mean(FLO_E), Coef_var = cv(FLO_E))
ggplot(CV)+
  geom_boxplot(aes(y=Coef_var , x = REGIAO))+
    labs(x = "Macrorregião", y = "CV", title = "Coeficiente de variação para data de florescimento por genótipo")

CV<- IRR %>% group_by(GENOTIPO,ID_ENSAIO,REGIAO) %>% summarise(FLO_M = mean(FLO_E), Coef_var = cv(FLO_E))
ggplot(CV)+
  geom_boxplot(aes(y=Coef_var , x = REGIAO))+
    labs(x = "Macrorregião", y = "CV", title = "Coeficiente de variação para data de florescimento por genótipo dentro do ensaio")
```
```{r, message=F}
CV<- IRR %>% group_by(GENOTIPO,ID_ENSAIO,REGIAO) %>% summarise(FLO_M = mean(FLO_E), Coef_var = cv(FLO_E))
CV
```

## Boxplot


```{r}
# Variáveis com escala menor
Temporario<- IRR[,c(-1,-2,-3,-4,-5,-6,-7,-11,-15,-20,-23,-24,-25,-26,-27,-28,-29,-34,-35)] # retirando as variáveis com escala maior

boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores originais")

Temporario<- IRR_Medio[,c(-1,-2,-3,-4,-8,-12,-17,-20,-21,-22,-23,-24,-25,-26,-31,-32)] # retirando as variáveis com escala maior

boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio/região")

# filtrando por região
Temporario<- subset(IRR_Medio, (REGIAO == "Centro_Oeste"))
Temporario<- Temporario[,c(-1,-2,-3,-4,-8,-12,-17,-20,-21,-22,-23,-24,-25,-26,-31,-32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Centro-oeste")
Temporario<- subset(IRR_Medio, (REGIAO == "Norte"))
Temporario<- Temporario[,c(-1,-2,-3,-4,-8,-12,-17,-20,-21,-22,-23,-24,-25,-26,-31,-32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Norte")
Temporario<- subset(IRR_Medio, (REGIAO == "Nordeste"))
Temporario<- Temporario[,c(-1,-2,-3,-4,-8,-12,-17,-20,-21,-22,-23,-24,-25,-26,-31,-32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Nordeste")
Temporario<- subset(IRR_Medio, (REGIAO == "Sul"))
Temporario<- Temporario[,c(-1,-2,-3,-4,-8,-12,-17,-20,-21,-22,-23,-24,-25,-26,-31,-32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Sul")
Temporario<- subset(IRR_Medio, (REGIAO == "Sudeste"))
Temporario<- Temporario[,c(-1,-2,-3,-4,-8,-12,-17,-20,-21,-22,-23,-24,-25,-26,-31,-32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Sudeste")

```
```{r}
# variáveis com escala maior
Temporario<- IRR[,c(11,15,20,23,24,25,26,27,28,29,34,35)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores originais")
Temporario<- IRR_Medio[,c(8,12,17,20,21,22,23,24,25,26,31,32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio/região")

# filtrando por região
Temporario<- subset(IRR_Medio, (REGIAO == "Centro_Oeste"))
Temporario<- Temporario[,c(8,12,17,20,21,22,23,24,25,26,31,32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Centro-oeste")
Temporario<- subset(IRR_Medio, (REGIAO == "Norte"))
Temporario<- Temporario[,c(8,12,17,20,21,22,23,24,25,26,31,32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Norte")
Temporario<- subset(IRR_Medio, (REGIAO == "Nordeste"))
Temporario<- Temporario[,c(8,12,17,20,21,22,23,24,25,26,31,32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Nordeste")
Temporario<- subset(IRR_Medio, (REGIAO == "Sul"))
Temporario<- Temporario[,c(8,12,17,20,21,22,23,24,25,26,31,32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Sul")
Temporario<- subset(IRR_Medio, (REGIAO == "Sudeste"))
Temporario<- Temporario[,c(8,12,17,20,21,22,23,24,25,26,31,32)] # retirando as variáveis com escala maior
boxplot(Temporario, horizontal = T, las = 1, cex.axis=0.55, main = "Boxplot com os valores das médias por genótipo/ensaio para Sudeste")

```
## Matrix de correlação

```{r}
Temporario<-IRR_Medio[,c(-1,-2,-3)]
chart.Correlation(Temporario, histogram = T)
title("Matrix de correlação", line = 1)

Temporario<- subset(IRR_Medio, (REGIAO == "Centro_Oeste"))
Temporario<- Temporario[,c(-1,-2,-3)]
chart.Correlation(Temporario, histogram = T)
title("Matrix de correlação Centro-oeste", line = 1)

Temporario<- subset(IRR_Medio, (REGIAO == "Norte"))
Temporario<- Temporario[,c(-1,-2,-3)]
chart.Correlation(Temporario, histogram = T)
title("Matrix de correlação Norte", line = 1)

Temporario<- subset(IRR_Medio, (REGIAO == "Nordeste"))
Temporario<- Temporario[,c(-1,-2,-3)]
chart.Correlation(Temporario, histogram = T)
title("Matrix de correlação Nordeste", line = 1)

Temporario<- subset(IRR_Medio, (REGIAO == "Sul"))
Temporario<- Temporario[,c(-1,-2,-3)]
chart.Correlation(Temporario, histogram = T)
title("Matrix de correlação Sul", line = 1)

Temporario<- subset(IRR_Medio, (REGIAO == "Sudeste"))
Temporario<- Temporario[,c(-1,-2,-3)]
chart.Correlation(Temporario, histogram = T)
title("Matrix de correlação Sudeste", line = 1)
```


##  Predictive Power Score (PPS)

```{r}

Temporario<-IRR_Medio[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario, y  = "FLO_M" ) + 
 ggplot2 :: labs ( title  =  'PPS com dados não regionalizados' )


Temporario<- subset(IRR_Medio, (REGIAO == "Centro_Oeste"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario, y  = "FLO_M" ) + 
 ggplot2 :: labs ( title  =  'PPS Centro-Oeste' )

Temporario<- subset(IRR_Medio, (REGIAO == "Norte"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario, y  = "FLO_M"  ) + 
 ggplot2 :: labs ( title  =  'PPS Norte' )

Temporario<- subset(IRR_Medio, (REGIAO == "Nordeste"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario, y  = "FLO_M" ) + 
 ggplot2 :: labs ( title  =  'PPS Nordeste' )

Temporario<- subset(IRR_Medio, (REGIAO == "Sul"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario, y  = "FLO_M" ) + 
 ggplot2 :: labs ( title  =  'PPS Sul' )

Temporario<- subset(IRR_Medio, (REGIAO == "Sudeste"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario, y  = "FLO_M") + 
 ggplot2 :: labs ( title  =  'PPS Sudeste' )

```

```{r}


Temporario<-IRR_Medio[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario) + 
 ggplot2 :: labs ( title  =  'PPS com dados não regionalizados' )

Temporario<- subset(IRR_Medio, (REGIAO == "Centro_Oeste"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario ) + 
 ggplot2 :: labs ( title  =  'PPS Centro-Oeste' )

Temporario<- subset(IRR_Medio, (REGIAO == "Norte"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario ) + 
 ggplot2 :: labs ( title  =  'PPS Norte' )

Temporario<- subset(IRR_Medio, (REGIAO == "Nordeste"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario ) + 
 ggplot2 :: labs ( title  =  'PPS Nordeste' )

Temporario<- subset(IRR_Medio, (REGIAO == "Sul"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario ) + 
 ggplot2 :: labs ( title  =  'PPS Sul' )

Temporario<- subset(IRR_Medio, (REGIAO == "Sudeste"))
Temporario<- Temporario[,c(-1,-2,-3)]
ppsr :: visualize_pps ( df = Temporario ) + 
 ggplot2 :: labs ( title  =  'PPS Sudeste' )

```

