---
title: "GAM_IRR_SUL"
author: "Gutemberg Resende Honorio Filho"
date: "16/08/2021"
output: html_document
---

```{r}
library(tidyverse)

#library(mgcv)
library(gam)

if(!require(caTools)) install.packages("caTools")

if(!require(stats)) install.packages("stats")
if(!require(Hmisc)) install.packages("Hmisc")

```

# DADOS
```{r Diretório} 

# DIRETÓRIO DOS DADOS 

Tabelabruta<- read.csv("d:/Users/Cristiane Resende/Desktop/Gutemberg Honorio/Mestrado/Repositorio_4/Analise_e_modelagem_Arroz/Merge_1980_2018.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE) # tabela com os dados originais

# criando coluna com macrorregiões

Tabelabruta<- mutate(Tabelabruta,REGIAO = case_when(UF == 'GO'| UF == 'DF' |UF == 'MS' | UF == 'MT' ~ 'Centro-oeste',
                              UF == 'AL'| UF == 'BA' |UF == 'CE' | UF == 'MA' | UF == 'PB' | UF == 'PE' | UF == 'PI' | UF == 'RN' | UF == 'SE' ~ 'Nordeste',
                              UF == 'AC' | UF == 'AM' | UF == 'AP' | UF == 'PA' | UF == 'RO' | UF == 'RR' | UF == 'TO' ~ 'Norte',
                              UF == 'ES' | UF == 'MG' | UF == 'SP' | UF == 'RJ' ~ 'Sudeste',
                              UF == 'RS' | UF == 'SC' | UF == 'PR' ~ 'Sul'))

# Tabelas acessório

TabelabrutaIRR = subset(Tabelabruta, SIST_CULT == "IRRIGATED") # Somente Irrigado
TabelabrutaTA = subset(Tabelabruta, SIST_CULT == "UPLAND") # Somente Terras altas

# Filtrando os dados


IRR<-TabelabrutaIRR %>% mutate(UR_Media=(umidade_Media),UR_V=	(umidade_V), UR_fld_m=	(umidade_fld_m),	UR_R=	(umidade_R), Graus_dia_ciclo=(graus_dia_ciclo), Graus_dia_FLO=(graus_dia_FLO+graus_dia_IP))

IRR <- select(IRR,latitude, longitude, GENOTIPO, ID_ENSAIO,ano, Altitude, REGIAO, UF, FLO_E, Tmax_Maxima ,Tmax_fld_m ,	Tmax_R,	Tmax_ACC_R, Tmax_Minima,	Tmax_Media,Tmax_V ,Tmax_ACC_V,	Tmin_Maxima,Tmin_Minima ,	Tmin_Media ,	Tmin_V ,	Tmin_ACC_V , Tmin_fld_m ,	Tmin_R,	Tmin_ACC_R , Chuva_ACC ,	Chuva_ACC_V, Chuva_ACC_R, Rad_ACC_R ,	Rad_ACC ,	Rad_ACC_V, UR_Media, UR_V, UR_fld_m,	UR_R, Graus_dia_ciclo, Graus_dia_FLO)


rm(TabelabrutaIRR,TabelabrutaTA,Tabelabruta)

# Removendo os genótipos que não serão estudados

IRR = IRR[IRR$GENOTIPO %in% c("ALIANCA",	"AVAXI CL",	"BR IRGA 409",	"BR IRGA 410",	"BR IRGA 412",	"BR IRGA 414",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS A704",	"BRS ALVORADA",	"BRS BIGUA",	"BRS CATIANA",	"BRS CIRAD 302",	"BRS FORMOSO",	"BRS FRONTEIRA",	"BRS GUARA",	"BRS JABURU",	"BRS JACANA",	"BRS PAMPA",	"BRS PAMPEIRA",	"BRS PELOTA",	"BRS QUERENCIA",	"BRS SINUELO CL",	"BRS TROPICAL",	"BRSMG RUBELITA",	"CICA 8",	"CT8452",	"DIAMANTE",	"EEA34",	"EMPASC 101",	"EMPASC 102",	"EPAGRI 108",	"EPAGRI 109",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"H6",	"H7 CL",	"IAC1289",	"IAC1298",	"IAC1299",	"IAC1307",	"IAC1311",	"IAPAR 58",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 428",	"IRGA 429",	"IRGA 430",	"IRGA97-05",	"IRGA97-10",	"IRGA97-11",	"IRGA97-28",	"JAVAE",	"JEQUITIBA",	"MARAJO",	"METICA 1",	"MOXOTO",	"OUROMINAS",	"PR267",	"PR268",	"PR306",	"PR331",	"PR349",	"PR380",	"PR498",	"PR631",	"PR67",	"PUITA INTA CL",	"RORAIMA",	"SAO FRANCISCO",	"SC138",	"SC173",	"SC237",	"SC240",	"SC250",	"SCS 112",	"SCS 114 ANDOSAN",	"SCS 116 SATORU",	"SCS 121 CL",	"SCSBRS 111",	"SCSBRS 113 TIO TAKA",	"SCSBRS PIRACEMA",	"SG11551",	"URUCUI"),]
IRR = IRR[IRR$UF!="MT",]

# Filtrando e gerando médias

IRR_Medio<- IRR %>% group_by(ID_ENSAIO, GENOTIPO, REGIAO) %>% summarise(  FLO_M= mean(FLO_E),  latitude= mean(latitude), longitude = mean(longitude), Altitude = mean(Altitude), Tmax_Maxima = mean(Tmax_Maxima) ,Tmax_fld_m = mean(Tmax_fld_m ),	Tmax_R= mean( Tmax_R),	Tmax_ACC_R= mean(Tmax_ACC_R ), Tmax_Minima= mean(Tmax_Minima ),	Tmax_Media= mean( Tmax_Media),Tmax_V = mean(Tmax_V ),Tmax_ACC_V= mean(Tmax_ACC_V ),	Tmin_Maxima= mean(Tmin_Maxima ),Tmin_Minima = mean(Tmin_Minima ),	Tmin_Media = mean(Tmin_Media ),	Tmin_V = mean(Tmin_V ),	Tmin_ACC_V = mean(Tmin_ACC_V ), Tmin_fld_m = mean( Tmin_fld_m),	Tmin_R= mean(Tmin_R ),	Tmin_ACC_R = mean(Tmin_ACC_R ), Chuva_ACC = mean(Chuva_ACC ),	Chuva_ACC_V= mean(Chuva_ACC_V ), Chuva_ACC_R= mean(Chuva_ACC_R ), Rad_ACC_R = mean(Rad_ACC_R ),	Rad_ACC = mean(Rad_ACC ),	Rad_ACC_V= mean(Rad_ACC_V ), UR_Media= mean( UR_Media), UR_V= mean( UR_V), UR_fld_m= mean(UR_fld_m ),	UR_R= mean(UR_R ), Graus_dia_ciclo= mean(Graus_dia_ciclo ), Graus_dia_FLO= mean(Graus_dia_FLO ))

# separando por macrorregião

Sul<- subset(IRR_Medio, (REGIAO == "Sul")) # filtrando por região
```


```{r}
Temporario<- Sul[,c(-1,-3)]

```
```{r}
table(Temporario$GENOTIPO)
```
```{r}
Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("SAO FRANCISCO", "SCSBRS 111","CT8452","DIAMANTE","MOXOTO","EEA34","EPAGRI 109", "BRS JABURU","PR331")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, 0 , Genotipos))

Temporario <- Temporario[Temporario$GENOTIPO != 0,]

table(Temporario$GENOTIPO)

```
# STEP
```{r}
modelo_GAM_Sul<- gam(FLO_M~ GENOTIPO, family = gaussian, data= Temporario)

Step1<-step.Gam(modelo_GAM_Sul ,scope = list ( "latitude"=~1+ latitude ,"longitude"=~1+longitude , "Altitude"=~1+ Altitude, "Tmax_Maxima"=~1+ Tmax_Maxima +s(Tmax_Maxima , 4), "Tmax_fld_m"=~1+ Tmax_fld_m +s(Tmax_fld_m , 4), "Tmax_R"=~1+ Tmax_R +s(Tmax_R , 4), "Tmax_ACC_R"=~1+ Tmax_ACC_R +s(Tmax_ACC_R , 4), "Tmax_Minima"  =~1+ Tmax_Minima +s(Tmax_Minima , 4),    "Tmax_Media"=~1+ Tmax_Media +s(Tmax_Media , 4), "Tmax_V"=~1+ Tmax_V +s(Tmax_V , 4), "Tmax_ACC_V"=~1+ Tmax_ACC_V +s(Tmax_ACC_V , 4), "Tmin_Maxima"    =~1+ Tmin_Maxima +s(Tmin_Maxima , 4), "Tmin_Minima" =~1+ Tmin_Minima +s(Tmin_Minima , 4), "Tmin_Media"=~1+ Tmin_Media +s(Tmin_Media , 4), "Tmin_V"=~1+ Tmin_V +s(Tmin_V , 4), "Tmin_ACC_V"=~1+ Tmin_ACC_V +s(Tmin_ACC_V , 4), "Tmin_fld_m"=~1+ Tmin_fld_m +s(Tmin_fld_m , 4), "Tmin_R"=~1+ Tmin_R +s(Tmin_R , 4), "Tmin_ACC_R"=~1+ Tmin_ACC_R +s(Tmin_ACC_R , 4),  "Chuva_ACC"=~1+ Chuva_ACC +s(Chuva_ACC , 4), "Chuva_ACC_V"   =~1+ Chuva_ACC_V +s(Chuva_ACC_V , 4),   "Chuva_ACC_R"   =~1+ Chuva_ACC_R +s(Chuva_ACC_R , 4),   "Rad_ACC_R"=~1+ Rad_ACC_R +s(Rad_ACC_R , 4), "Rad_ACC"=~1+ Rad_ACC +s(Rad_ACC , 4), "Rad_ACC_V"=~1+ Rad_ACC_V +s(Rad_ACC_V , 4), "UR_Media" =~1+ UR_Media +s(UR_Media , 4),  "UR_V"=~1+ UR_V +s(UR_V , 4), "UR_fld_m"=~1+ UR_fld_m +s(UR_fld_m , 4), "UR_R"=~1+ UR_R +s(UR_R , 4), "Graus_dia_ciclo"=~1+ Graus_dia_ciclo +s(Graus_dia_ciclo , 4),  "Graus_dia_FLO"  =~1+ Graus_dia_FLO +s(Graus_dia_FLO, 4)))
   
```



```{r}
Step1$formula
```

```{r}
 detach("package:gam", unload = TRUE)
library(mgcv)
```

# MODELO
```{r}
modelo_GAM_Sul<- gam(FLO_M ~  GENOTIPO + Tmax_Media + Tmin_V + Tmin_ACC_V + Tmin_ACC_R + 
    UR_R, family = gaussian, data = Temporario)

summary(modelo_GAM_Sul)
```



```{r}
Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c( "AVAXI CL", "BRS A701 CL", "BRS PAMPA", "BRS PELOTA","BRS PELOTA", "H7 CL", "IRGA 417","JAVAE","PUITA INTA CL"
)

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

modelo_GAM_Sul<- gam(FLO_M ~  GENOTIPO + Tmax_Media + Tmin_V + Tmin_ACC_V + Tmin_ACC_R + 
    UR_R, family = gaussian, data = Temporario)

summary(modelo_GAM_Sul)
```
```{r}
Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c( "JEQUITIBA"
)

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

modelo_GAM_Sul<- gam(FLO_M ~  GENOTIPO + Tmax_Media + Tmin_V + Tmin_ACC_V + Tmin_ACC_R + 
    UR_R, family = gaussian, data = Temporario)

summary(modelo_GAM_Sul)
```

```{r}

modelo_GAM_Sul<- gam(FLO_M ~  GENOTIPO + Tmax_Media + Tmin_V + Tmin_ACC_V + Tmin_ACC_R + 
    UR_R, family = gaussian, data = Temporario)

modelo_GAM_Sul1	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	Tmin_V + 	Tmin_ACC_V + 	Tmin_ACC_R + 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul2	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	s(Tmin_V )+ 	Tmin_ACC_V + 	Tmin_ACC_R + 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul3	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	Tmin_V + 	s(Tmin_ACC_V )+ 	Tmin_ACC_R + 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul4	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	Tmin_V + 	Tmin_ACC_V + 	s(Tmin_ACC_R )+ 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul5	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	Tmin_V + 	Tmin_ACC_V + 	Tmin_ACC_R + 	s(UR_R)	, family = gaussian, data = Temporario)

modelo_GAM_Sul6	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	s(Tmin_V )+ 	Tmin_ACC_V + 	Tmin_ACC_R + 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul7	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	Tmin_V + 	s(Tmin_ACC_V )+ 	Tmin_ACC_R + 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul8	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	Tmin_V + 	Tmin_ACC_V + 	s(Tmin_ACC_R )+ 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul9	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	Tmin_V + 	Tmin_ACC_V + 	Tmin_ACC_R + 	s(UR_R)	, family = gaussian, data = Temporario)
modelo_GAM_Sul10	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	s(Tmin_V )+ 	s(Tmin_ACC_V )+ 	Tmin_ACC_R + 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul11	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	s(Tmin_V )+ 	Tmin_ACC_V + 	s(Tmin_ACC_R )+ 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul12	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	s(Tmin_V )+ 	Tmin_ACC_V + 	Tmin_ACC_R + 	s(UR_R)	, family = gaussian, data = Temporario)
							
modelo_GAM_Sul13	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	Tmin_V + 	s(Tmin_ACC_V )+ 	s(Tmin_ACC_R )+ 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul14	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	Tmin_V + 	s(Tmin_ACC_V )+ 	Tmin_ACC_R + 	s(UR_R)	, family = gaussian, data = Temporario)
								
modelo_GAM_Sul15	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media + 	Tmin_V + 	Tmin_ACC_V + 	s(Tmin_ACC_R )+ 	s(UR_R)	, family = gaussian, data = Temporario)
								
modelo_GAM_Sul16	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	s(Tmin_V )+ 	s(Tmin_ACC_V )+ 	Tmin_ACC_R + 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul17	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	s(Tmin_V )+ 	Tmin_ACC_V + 	s(Tmin_ACC_R )+ 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul18	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	s(Tmin_V )+ 	Tmin_ACC_V + 	Tmin_ACC_R + 	s(UR_R)	, family = gaussian, data = Temporario)
								
modelo_GAM_Sul19	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	Tmin_V + 	s(Tmin_ACC_V )+ 	s(Tmin_ACC_R )+ 	UR_R	, family = gaussian, data = Temporario)
modelo_GAM_Sul20	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	Tmin_V + 	s(Tmin_ACC_V )+ 	Tmin_ACC_R + 	s(UR_R)	, family = gaussian, data = Temporario)

modelo_GAM_Sul21	<- gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	s(Tmin_V) + 	s(Tmin_ACC_V )+ 	s(Tmin_ACC_R) + 	s(UR_R)	, family = gaussian, data = Temporario)


modelo_GAM_Sul$aic
modelo_GAM_Sul1$aic
modelo_GAM_Sul2$aic
modelo_GAM_Sul3$aic
modelo_GAM_Sul4$aic
modelo_GAM_Sul5$aic

modelo_GAM_Sul6$aic
modelo_GAM_Sul7$aic
modelo_GAM_Sul8$aic
modelo_GAM_Sul9$aic

modelo_GAM_Sul10$aic
modelo_GAM_Sul11$aic
modelo_GAM_Sul12$aic
modelo_GAM_Sul13$aic
modelo_GAM_Sul14$aic
modelo_GAM_Sul15$aic

modelo_GAM_Sul16$aic
modelo_GAM_Sul17$aic
modelo_GAM_Sul18$aic
modelo_GAM_Sul19$aic

modelo_GAM_Sul20$aic

modelo_GAM_Sul21$aic
```

```{r}
a	<-	summary(	modelo_GAM_Sul)	
b	<-	summary(	modelo_GAM_Sul1)	
c	<-	summary(	modelo_GAM_Sul2)	
d	<-	summary(	modelo_GAM_Sul3)	
e	<-	summary(	modelo_GAM_Sul4)	
f	<-	summary(	modelo_GAM_Sul5)	
g	<-	summary(	modelo_GAM_Sul6)	
h	<-	summary(	modelo_GAM_Sul7)	
i	<-	summary(	modelo_GAM_Sul8)	
j	<-	summary(	modelo_GAM_Sul9)	
k	<-	summary(	modelo_GAM_Sul10)	
l	<-	summary(	modelo_GAM_Sul11)	
m	<-	summary(	modelo_GAM_Sul12)	
n	<-	summary(	modelo_GAM_Sul13)	
o	<-	summary(	modelo_GAM_Sul14)	
p	<-	summary(	modelo_GAM_Sul15)	
q	<-	summary(	modelo_GAM_Sul16)	
r	<-	summary(	modelo_GAM_Sul17)	
s	<-	summary(	modelo_GAM_Sul18)	
t	<-	summary(	modelo_GAM_Sul19)	
u	<-	summary(	modelo_GAM_Sul20)	
v	<-	summary(	modelo_GAM_Sul21)	

a$dev.expl
b$dev.expl
c$dev.expl
d$dev.expl
e$dev.expl
f$dev.expl
g$dev.expl
h$dev.expl
i$dev.expl
j$dev.expl
k$dev.expl
l$dev.expl
m$dev.expl
n$dev.expl
o$dev.expl
p$dev.expl
q$dev.expl
r$dev.expl
s$dev.expl
t$dev.expl
u$dev.expl
v$dev.expl

```

```{r}
modelo_GAM_Sul22	<- gam(FLO_M ~  GENOTIPO + 	Tmax_Media+ 	s(Tmin_V) + 	s(Tmin_ACC_V )+ 	s(Tmin_ACC_R) + 	s(UR_R)	, family = gaussian, data = Temporario)
summary(modelo_GAM_Sul22)
```



```{r}
plot(modelo_GAM_Sul21, rug = TRUE, residuals = TRUE,
     pch = 1, cex = 1)
```
```{r}
plot.gam(modelo_GAM_Sul21)
```

```{r}

Temporario<- Temporario

Temporario$`Yhat` <-predict ( modelo_GAM_Sul21, Temporario)
Temporario$`Y_yhat` = c(Temporario$FLO_M - Temporario$Yhat)


  
  
  boxplot(Temporario$Y_yhat, main = "Todos os genótipos", xlab = "Y - Yhat" , ylab = "Dias pós emergência", cex.lab = 1.5)
  plot(y = Temporario$FLO_M, x = Temporario$Yhat,  main = "Todos os genótipos", xlab = "Valores preditos", ylab = "Valores observados", pch = 20, 
     col = "black" , cex.lab = 1.5) 
```
 



```{r}
summary(modelo_GAM_Sul21)

```

## BIC


```{r}
BIC(modelo_GAM_Sul21)
BIC(modelo_Sul)
```



# Validação cruzada

```{r}
Genotipos  <- Sul$GENOTIPO
SELECAO_GEN <- c("SAO FRANCISCO", "SCSBRS 111","CT8452","DIAMANTE","MOXOTO","EEA34","EPAGRI 109", "BRS JABURU","PR331")

Sul$GENOTIPO <- c(ifelse(Sul$GENOTIPO %in% SELECAO_GEN, 0 , Genotipos))

Sul <- Sul[Sul$GENOTIPO != 0,]
```


## LM
```{r}
res_Sul_LM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Sul$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Sul$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Sul[Sul$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Sul[Sul$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("AVAXI CL","BRS PAMPA",	"BRS PELOTA",	"EEA34",	"H7 CL",	"IRGA 417",	"JAVAE",	"PUITA INTA CL", "BRS A701 CL")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))



test = lm(FLO_M ~ GENOTIPO + Tmin_V + Tmin_ACC_V + Tmin_ACC_R + Chuva_ACC_R + 
    UR_V  , data = treinamento)



Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("AVAXI CL","BRS PAMPA",	"BRS PELOTA",	"EEA34",	"H7 CL",	"IRGA 417",	"JAVAE",	"PUITA INTA CL", "BRS A701 CL")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Sul_LM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```

## GAM
```{r}
res_Sul_GAM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Sul$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Sul$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Sul[Sul$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Sul[Sul$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c( "AVAXI CL", "BRS A701 CL", "BRS PAMPA", "BRS PELOTA","BRS PELOTA", "H7 CL", "IRGA 417","JAVAE","PUITA INTA CL","JEQUITIBA")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	s(Tmin_V) + 	s(Tmin_ACC_V )+ 	s(Tmin_ACC_R) + 	s(UR_R)	, family = gaussian, data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c( "AVAXI CL", "BRS A701 CL", "BRS PAMPA", "BRS PELOTA","BRS PELOTA", "H7 CL", "IRGA 417","JAVAE","PUITA INTA CL","JEQUITIBA")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Sul_GAM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```
## ERRO
```{r}
GAM<- data.frame("Erro" = res_Sul_GAM, "Modelo" = "GAM")
LM<- data.frame("Erro" = res_Sul_LM, "Modelo" = "LM")


val<- data.frame()
val<- data.frame("Erro" = c(LM$Erro,GAM$Erro), "Modelo" = c(LM$Modelo,GAM$Modelo) )

v3<-ggplot(data = val, aes(y = Erro, x= Modelo, color=Modelo, fill = Modelo )) +
   geom_boxplot(
    width = .2, fill = "white",
    size = 1.5, outlier.shape = NA
  ) +
  ggdist::stat_halfeye(
    adjust = .60, 
    width = .55, 
    color = NA, 
    position = position_nudge(x = .14)
  ) +
  geom_point(
    position = position_nudge(x = -.22),
    shape = 95, size = 12, alpha = .25
  )+
  labs(y= "Average absolute error (days)", x="")+
  guides(color=FALSE)+
  scale_color_viridis_d()+
   scale_fill_viridis_d()+
   theme_classic(base_size = 12)+
 theme(legend.position="none")

```





```{r}
#install.packages('mgcViz')

#library(mgcViz)
viz <- getViz(modelo_GAM_Sul)
trt<-plot(viz, allTerms = F) +
  l_ciPoly()+
    l_fitLine(colour = "blue") + l_rug(mapping = aes(x=x, y=y)) +
    geom_hline(yintercept = 0, linetype = 2, alpha=0.4)+
     theme_classic()


trt[["plots"]][[1]][["ggObj"]][["labels"]][["x"]]<-c("Tmax_M (ºC)")
trt[["plots"]][[1]][["ggObj"]][["labels"]][["title"]]<-c("(A)")

trt[["plots"]][[2]][["ggObj"]][["labels"]][["x"]]<-c("Tmin_V (ºC)")
trt[["plots"]][[2]][["ggObj"]][["labels"]][["title"]]<-c("(B)")

trt[["plots"]][[3]][["ggObj"]][["labels"]][["x"]]<-c("Tmin_ACC_V (ºC)")
trt[["plots"]][[3]][["ggObj"]][["labels"]][["title"]]<-c("(C)")

trt[["plots"]][[4]][["ggObj"]][["labels"]][["x"]]<-c("Tmin_ACC_R (ºC)")
trt[["plots"]][[4]][["ggObj"]][["labels"]][["title"]]<-c("(D)")

trt[["plots"]][[5]][["ggObj"]][["labels"]][["x"]]<-c("HU_R (%)")
trt[["plots"]][[5]][["ggObj"]][["labels"]][["title"]]<-c("(E)")

print(trt, pages = 1)

```

```{r}
library(forcats)
((p_Centro_oeste2+p_Norte2+p_Sul2)/(p_sudeste2+p_nordeste2))+plot_annotation(tag_levels = 'A', tag_prefix = '(', tag_suffix = ')')
```


```{r}

Temporario<- Sul[,c(-1,-3)]

Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("AVAXI CL", "BRS A701 CL", "BRS PAMPA", "BRS PELOTA","BRS PELOTA", "H7 CL", "IRGA 417","JAVAE","PUITA INTA CL","JEQUITIBA")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

Temporario1<- summary(modelo_GAM_Sul)
Temporario1<-data.frame(Temporario1[["p.coeff"]])
Temporario1<- data.frame("variaveis" = row.names(Temporario1), "estimativas" = Temporario1$Temporario1...p.coeff...)
Temporario1<- Temporario1[c(-1),]

Temporario1$variaveis<-gsub("GENOTIPO", "", Temporario1$variaveis)

Temporario1$crescimento = as.factor(ifelse(Temporario1$estimativas > 0, yes = 1, no = 0))

p_Sul2<-ggplot(data = Temporario1, aes(x=  fct_reorder(variaveis, estimativas, .desc = TRUE), y = estimativas))+
  geom_col(aes(fill = crescimento))+
  labs(x = "", y = "Pre and post flowering days")+
 coord_flip()+
        geom_hline(yintercept = 0) +
  guides(fill = FALSE) +
  scale_fill_manual(values = c("firebrick", "dodgerblue4"))+
  theme_bw()


```



```{r}
(bb1|bb2|bb3|bb4|bb5)/(p_Centro_oeste2|p_Norte2|p_Sul2|p_sudeste2|p_nordeste2)
```


(bb1|bb2|bb3|bb4|bb5)/(p_Centro_oeste2|p_Norte2|p_Sul2|p_sudeste2|p_nordeste2)












