---
title: "GAM_IRR_CENTRO_OESTE"
author: "Gutemberg Resende Honorio Filho"
date: "16/08/2021"
output: html_document
---

```{r}
library(tidyverse)

#library(mgcv)
library(gam)

if(!require(caTools)) install.packages("caTools")
if(!require(stats)) install.packages("stats")
if(!require(Hmisc)) install.packages("Hmisc")

```

# DADOS
```{r Diretório} 

# DIRETÓRIO DOS DADOS 

Tabelabruta<- read.csv("d:/Users/Cristiane Resende/Desktop/Gutemberg Honorio/Mestrado/Repositorio_4/Analise_e_modelagem_Arroz/Merge_1980_2018.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE) # tabela com os dados originais

# criando coluna com macrorregiões

Tabelabruta<- mutate(Tabelabruta,REGIAO = case_when(UF == 'GO'| UF == 'DF' |UF == 'MS' | UF == 'MT' ~ 'Centro-oeste',
                              UF == 'AL'| UF == 'BA' |UF == 'CE' | UF == 'MA' | UF == 'PB' | UF == 'PE' | UF == 'PI' | UF == 'RN' | UF == 'SE' ~ 'Nordeste',
                              UF == 'AC' | UF == 'AM' | UF == 'AP' | UF == 'PA' | UF == 'RO' | UF == 'RR' | UF == 'TO' ~ 'Norte',
                              UF == 'ES' | UF == 'MG' | UF == 'SP' | UF == 'RJ' ~ 'Sudeste',
                              UF == 'RS' | UF == 'SC' | UF == 'PR' ~ 'Sul'))

# Tabelas acessório

TabelabrutaIRR = subset(Tabelabruta, SIST_CULT == "IRRIGATED") # Somente Irrigado
TabelabrutaTA = subset(Tabelabruta, SIST_CULT == "UPLAND") # Somente Terras altas

# Filtrando os dados


IRR<-TabelabrutaIRR %>% mutate(UR_Media=(umidade_Media),UR_V=	(umidade_V), UR_fld_m=	(umidade_fld_m),	UR_R=	(umidade_R), Graus_dia_ciclo=(graus_dia_ciclo), Graus_dia_FLO=(graus_dia_FLO+graus_dia_IP))

IRR <- select(IRR,latitude, longitude, GENOTIPO, ID_ENSAIO,ano, Altitude, REGIAO, UF, FLO_E, Tmax_Maxima ,Tmax_fld_m ,	Tmax_R,	Tmax_ACC_R, Tmax_Minima,	Tmax_Media,Tmax_V ,Tmax_ACC_V,	Tmin_Maxima,Tmin_Minima ,	Tmin_Media ,	Tmin_V ,	Tmin_ACC_V , Tmin_fld_m ,	Tmin_R,	Tmin_ACC_R , Chuva_ACC ,	Chuva_ACC_V, Chuva_ACC_R, Rad_ACC_R ,	Rad_ACC ,	Rad_ACC_V, UR_Media, UR_V, UR_fld_m,	UR_R, Graus_dia_ciclo, Graus_dia_FLO)


rm(TabelabrutaIRR,TabelabrutaTA,Tabelabruta)

# Removendo os genótipos que não serão estudados

IRR = IRR[IRR$GENOTIPO %in% c("ALIANCA",	"AVAXI CL",	"BR IRGA 409",	"BR IRGA 410",	"BR IRGA 412",	"BR IRGA 414",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS A704",	"BRS ALVORADA",	"BRS BIGUA",	"BRS CATIANA",	"BRS CIRAD 302",	"BRS FORMOSO",	"BRS FRONTEIRA",	"BRS GUARA",	"BRS JABURU",	"BRS JACANA",	"BRS PAMPA",	"BRS PAMPEIRA",	"BRS PELOTA",	"BRS QUERENCIA",	"BRS SINUELO CL",	"BRS TROPICAL",	"BRSMG RUBELITA",	"CICA 8",	"CT8452",	"DIAMANTE",	"EEA34",	"EMPASC 101",	"EMPASC 102",	"EPAGRI 108",	"EPAGRI 109",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"H6",	"H7 CL",	"IAC1289",	"IAC1298",	"IAC1299",	"IAC1307",	"IAC1311",	"IAPAR 58",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 428",	"IRGA 429",	"IRGA 430",	"IRGA97-05",	"IRGA97-10",	"IRGA97-11",	"IRGA97-28",	"JAVAE",	"JEQUITIBA",	"MARAJO",	"METICA 1",	"MOXOTO",	"OUROMINAS",	"PR267",	"PR268",	"PR306",	"PR331",	"PR349",	"PR380",	"PR498",	"PR631",	"PR67",	"PUITA INTA CL",	"RORAIMA",	"SAO FRANCISCO",	"SC138",	"SC173",	"SC237",	"SC240",	"SC250",	"SCS 112",	"SCS 114 ANDOSAN",	"SCS 116 SATORU",	"SCS 121 CL",	"SCSBRS 111",	"SCSBRS 113 TIO TAKA",	"SCSBRS PIRACEMA",	"SG11551",	"URUCUI"),]
IRR = IRR[IRR$UF!="MT",]

# Filtrando e gerando médias

IRR_Medio<- IRR %>% group_by(ID_ENSAIO, GENOTIPO, REGIAO) %>% summarise(  FLO_M= mean(FLO_E),  latitude= mean(latitude), longitude = mean(longitude), Altitude = mean(Altitude), Tmax_Maxima = mean(Tmax_Maxima) ,Tmax_fld_m = mean(Tmax_fld_m ),	Tmax_R= mean( Tmax_R),	Tmax_ACC_R= mean(Tmax_ACC_R ), Tmax_Minima= mean(Tmax_Minima ),	Tmax_Media= mean( Tmax_Media),Tmax_V = mean(Tmax_V ),Tmax_ACC_V= mean(Tmax_ACC_V ),	Tmin_Maxima= mean(Tmin_Maxima ),Tmin_Minima = mean(Tmin_Minima ),	Tmin_Media = mean(Tmin_Media ),	Tmin_V = mean(Tmin_V ),	Tmin_ACC_V = mean(Tmin_ACC_V ), Tmin_fld_m = mean( Tmin_fld_m),	Tmin_R= mean(Tmin_R ),	Tmin_ACC_R = mean(Tmin_ACC_R ), Chuva_ACC = mean(Chuva_ACC ),	Chuva_ACC_V= mean(Chuva_ACC_V ), Chuva_ACC_R= mean(Chuva_ACC_R ), Rad_ACC_R = mean(Rad_ACC_R ),	Rad_ACC = mean(Rad_ACC ),	Rad_ACC_V= mean(Rad_ACC_V ), UR_Media= mean( UR_Media), UR_V= mean( UR_V), UR_fld_m= mean(UR_fld_m ),	UR_R= mean(UR_R ), Graus_dia_ciclo= mean(Graus_dia_ciclo ), Graus_dia_FLO= mean(Graus_dia_FLO ))

# separando por macrorregião

Centro_oeste<- subset(IRR_Medio, (REGIAO == "Centro-oeste")) # filtrando por região
```
```{r}
Temporario<- Centro_oeste[,c(-1,-3)]

```


```{r}
modelo_GAM_CENTRO_OESTE<- gam(FLO_M~ GENOTIPO, family = gaussian, data= Temporario)

Step1<-step.Gam(modelo_GAM_CENTRO_OESTE ,scope = list ( "latitude"=~1+ latitude ,"longitude"=~1+longitude , "Altitude"=~1+ Altitude, "Tmax_Maxima"=~1+ Tmax_Maxima +s(Tmax_Maxima , 4), "Tmax_fld_m"=~1+ Tmax_fld_m +s(Tmax_fld_m , 4), "Tmax_R"=~1+ Tmax_R +s(Tmax_R , 4), "Tmax_ACC_R"=~1+ Tmax_ACC_R +s(Tmax_ACC_R , 4), "Tmax_Minima"  =~1+ Tmax_Minima +s(Tmax_Minima , 4),    "Tmax_Media"=~1+ Tmax_Media +s(Tmax_Media , 4), "Tmax_V"=~1+ Tmax_V +s(Tmax_V , 4), "Tmax_ACC_V"=~1+ Tmax_ACC_V +s(Tmax_ACC_V , 4), "Tmin_Maxima"    =~1+ Tmin_Maxima +s(Tmin_Maxima , 4), "Tmin_Minima" =~1+ Tmin_Minima +s(Tmin_Minima , 4), "Tmin_Media"=~1+ Tmin_Media +s(Tmin_Media , 4), "Tmin_V"=~1+ Tmin_V +s(Tmin_V , 4), "Tmin_ACC_V"=~1+ Tmin_ACC_V +s(Tmin_ACC_V , 4), "Tmin_fld_m"=~1+ Tmin_fld_m +s(Tmin_fld_m , 4), "Tmin_R"=~1+ Tmin_R +s(Tmin_R , 4), "Tmin_ACC_R"=~1+ Tmin_ACC_R +s(Tmin_ACC_R , 4),  "Chuva_ACC"=~1+ Chuva_ACC +s(Chuva_ACC , 4), "Chuva_ACC_V"   =~1+ Chuva_ACC_V +s(Chuva_ACC_V , 4),   "Chuva_ACC_R"   =~1+ Chuva_ACC_R +s(Chuva_ACC_R , 4),   "Rad_ACC_R"=~1+ Rad_ACC_R +s(Rad_ACC_R , 4), "Rad_ACC"=~1+ Rad_ACC +s(Rad_ACC , 4), "Rad_ACC_V"=~1+ Rad_ACC_V +s(Rad_ACC_V , 4), "UR_Media" =~1+ UR_Media +s(UR_Media , 4),  "UR_V"=~1+ UR_V +s(UR_V , 4), "UR_fld_m"=~1+ UR_fld_m +s(UR_fld_m , 4), "UR_R"=~1+ UR_R +s(UR_R , 4), "Graus_dia_ciclo"=~1+ Graus_dia_ciclo +s(Graus_dia_ciclo , 4),  "Graus_dia_FLO"  =~1+ Graus_dia_FLO +s(Graus_dia_FLO, 4)))
   
```

```{r}
 detach("package:gam", unload = TRUE)
library(mgcv)
```

```{r}
Step1$formula
```

```{r}
modelo_GAM_CENTRO_OESTE<- gam(FLO_M ~ GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) + Chuva_ACC_V + s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = Temporario)

summary(modelo_GAM_CENTRO_OESTE)
```
```{r}
modelo_GAM_CENTRO_OESTE<- gam(FLO_M ~ GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) + s(Chuva_ACC_V) + s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = Temporario)

summary(modelo_GAM_CENTRO_OESTE)
```
```{r}
Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250"
)

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

modelo_GAM_CENTRO_OESTE<- gam(FLO_M ~ GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) + s(Chuva_ACC_V) + s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = Temporario)

summary(modelo_GAM_CENTRO_OESTE)
```

```{r}
modelo_GAM_CENTRO_OESTE<- gam(FLO_M ~ GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) + s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = Temporario)

summary(modelo_GAM_CENTRO_OESTE)
```

```{r}
Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("IRGA 427","SCSBRS 111")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

modelo_GAM_CENTRO_OESTE<- gam(FLO_M ~ GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) +  s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = Temporario)

summary(modelo_GAM_CENTRO_OESTE)
```
```{r}
Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("BRS PAMPA")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

modelo_GAM_CENTRO_OESTE<- gam(FLO_M ~ GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) +  s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = Temporario)

summary(modelo_GAM_CENTRO_OESTE)
```
```{r}
Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("IAC1289")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

modelo_GAM_CENTRO_OESTE<- gam(FLO_M ~ GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) +  s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = Temporario)

summary(modelo_GAM_CENTRO_OESTE)
```

```{r}
Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("PR67")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

modelo_GAM_CENTRO_OESTE<- gam(FLO_M ~ GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) +  s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = Temporario)

options(scipen = 999)
summary(modelo_GAM_CENTRO_OESTE)
```
```{r}
par(mfrow = c(2, 2))
gam.check(modelo_GAM_CENTRO_OESTE, old.style = T)
```

```{r}
plot(modelo_GAM_CENTRO_OESTE, rug = TRUE, residuals = TRUE,
     pch = 1, cex = 1)
```
```{r}

plot.gam(modelo_GAM_CENTRO_OESTE,  pages=1 )

```

```{r}

Temporario<- Temporario

Temporario$`Yhat` <-predict ( modelo_GAM_CENTRO_OESTE, Temporario)
Temporario$`Y_yhat` = c(Temporario$FLO_M - Temporario$Yhat)


  
  
  boxplot(Temporario$Y_yhat, main = "Todos os genótipos", xlab = "Y - Yhat" , ylab = "Dias pós emergência", cex.lab = 1.5)
  plot(y = Temporario$FLO_M, x = Temporario$Yhat,  main = "Todos os genótipos", xlab = "Valores preditos", ylab = "Valores observados", pch = 20, 
     col = "black" , cex.lab = 1.5) 
```
 


# Comparação com o modelo linear

## Modelo LM selecionado

Removendo os pontos de alavancagem 57, 60, 70 e 116 antes do ajuste, partindo das variáveis qualitativas

```{r}

Temporario <- Centro_oeste[,c(-1,-3)] # retirando as vaiáveis REGIAO e ID_ENSAIO
Temporario<- Temporario[c(-57, -60,-70,-116),]


Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409", "BR IRGA 410",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS CIRAD 302",	"BRS FRONTEIRA",	"BRS JACANA",	"BRS PAMPA",	"BRS PELOTA",	"BRS SINUELO CL",	"EMPASC 102",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"IAC1289",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 429",	"IRGA97-11",	"IRGA97-28",	"JEQUITIBA",	"PR306",	"PR349",	"PR498",	"PR631",	"SC240",	"SC250", "PR67","SCSBRS 111", "IAPAR 58", "SC237", "URUCUI" )

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

modelo_Centro_oeste<-lm(FLO_M~ GENOTIPO + longitude + Tmax_Maxima + Tmax_fld_m + Tmax_R + 
    Tmax_ACC_R + Tmax_Minima + Tmax_V + Tmax_ACC_V + Tmin_Maxima + 
    Tmin_Minima + Tmin_Media + Tmin_ACC_V + Tmin_fld_m + Tmin_R + 
    Tmin_ACC_R + Chuva_ACC_V , Temporario) 
summary(modelo_Centro_oeste)
```


## BIC


```{r}
BIC(modelo_GAM_CENTRO_OESTE)
BIC(modelo_Centro_oeste)
```




# Validação cruzada
## LM
```{r}
res_Centro_oeste_LM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Centro_oeste$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Centro_oeste$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Centro_oeste[Centro_oeste$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Centro_oeste[Centro_oeste$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409", "BR IRGA 410",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS CIRAD 302",	"BRS FRONTEIRA",	"BRS JACANA",	"BRS PAMPA",	"BRS PELOTA",	"BRS SINUELO CL",	"EMPASC 102",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"IAC1289",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 429",	"IRGA97-11",	"IRGA97-28",	"JEQUITIBA",	"PR306",	"PR349",	"PR498",	"PR631",	"SC240",	"SC250", "PR67","SCSBRS 111", "IAPAR 58", "SC237", "URUCUI" )

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = lm(FLO_M~ GENOTIPO + longitude + Tmax_Maxima + Tmax_fld_m + Tmax_R + 
    Tmax_ACC_R + Tmax_Minima + Tmax_V + Tmax_ACC_V + Tmin_Maxima + 
    Tmin_Minima + Tmin_Media + Tmin_ACC_V + Tmin_fld_m + Tmin_R + 
    Tmin_ACC_R + Chuva_ACC_V , data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409", "BR IRGA 410",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS CIRAD 302",	"BRS FRONTEIRA",	"BRS JACANA",	"BRS PAMPA",	"BRS PELOTA",	"BRS SINUELO CL",	"EMPASC 102",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"IAC1289",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 429",	"IRGA97-11",	"IRGA97-28",	"JEQUITIBA",	"PR306",	"PR349",	"PR498",	"PR631",	"SC240",	"SC250", "PR67","SCSBRS 111", "IAPAR 58", "SC237", "URUCUI" )

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Centro_oeste_LM[i] = mean(abs(predicao$FLO_M - aux) )
#print(i)
}
```

##GAM

```{r}
res_Centro_oeste_GAM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Centro_oeste$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Centro_oeste$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Centro_oeste[Centro_oeste$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Centro_oeste[Centro_oeste$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}
Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67"
)

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = gam(FLO_M~GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) +  s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67"
)

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Centro_oeste_GAM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```
## Erro
```{r}
GAM<- data.frame("Erro" = res_Centro_oeste_GAM, "Modelo" = "GAM")
LM<- data.frame("Erro" = res_Centro_oeste_LM, "Modelo" = "LM")


val<- data.frame()
val<- data.frame("Erro" = c(LM$Erro,GAM$Erro), "Modelo" = c(LM$Modelo,GAM$Modelo) )

v1<- ggplot(data = val, aes(y = Erro, x= Modelo, color=Modelo, fill = Modelo )) +
   geom_boxplot(
    width = .2, fill = "white",
    size = 1.5, outlier.shape = NA
  ) +
  ggdist::stat_halfeye(
    adjust = .60, 
    width = .55, 
    color = NA, 
    position = position_nudge(x = .14)
  ) +
  geom_point(
    position = position_nudge(x = -.22),
    shape = 95, size = 12, alpha = .25
  )+
  labs(y= "Average absolute error (days)", x="")+
  guides(color=FALSE)+
  scale_color_viridis_d()+
   scale_fill_viridis_d()+
   theme_classic(base_size = 12)+
 theme(legend.position="none")

```

```{r}
Predito<- data.frame("FLO" = aux, "Dado" = "Predição")
Obs<- data.frame("FLO" = predicao$FLO_M, "Dado" = "Observado")


Pred_obs<- data.frame()
Pred_obs<- data.frame("Predito" = aux, "Obs" = predicao$FLO_M )
Pred_obs$cont <- c(seq(1:nrow(Pred_obs)))

Pred_obs

ggplot(Pred_obs)+
  geom_line(aes(y=Predito, x=cont), color= "red")+
  geom_line(aes(y=Obs,x=cont), color= "blue")
```


```{r}
vis.gam ( modelo_GAM_CENTRO_OESTE, view = c ("Tmin_ACC_R", "Graus_dia_FLO" ) , theta = 50 , n.grid = 400 , border = NA ) 

vis.gam(modelo_GAM_CENTRO_OESTE,view = c ("Tmin_ACC_R", "Graus_dia_FLO" ) ,  n.grid =30, theta = 40, border = NA, phi = 32, zlab = "FLorescimento (DAE)", ticktype = "detailed", color = "heat")
```


```{r}
summary(modelo_GAM_CENTRO_OESTE)
```
# graficos 

```{r}
summary(modelo_GAM_Centro_oeste)

```


Tmin_V   Tmin_ACC_V  Tmin_R   Tmax_Minima   Tmin_ACC_R  Rad_ACC   Graus_dia_FLO
```{r}
modelo_Centro_oeste$xlevels
```


```{r}

Temporario<- Centro_oeste[,c(-1,-3)]


Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

Temporario1<- Temporario[Temporario$GENOTIPO %in% c("AA"),]
  media_Temporario1<- Temporario1 %>% group_by(GENOTIPO) %>% summarise(Tmin_V=mean(Tmin_V),   Tmin_ACC_V=mean(Tmin_ACC_V),  Tmin_R =mean(Tmin_R),    Tmax_Minima= mean(Tmax_Minima),   Tmin_ACC_R = mean(Tmin_ACC_R),  Rad_ACC=mean(Rad_ACC),   Graus_dia_FLO= mean(Graus_dia_FLO))
aux<-data.frame()
aux[1,1]<- media_Temporario1[1,1]

name<-colnames(media_Temporario1)
for (i in 2:8) {
  predicao<-media_Temporario1
  predicao<-predicao %>% mutate(predicao[i], predicao[i]+(predicao[i]*0.10))
  aux[1,i] = predict(modelo_GAM_Centro_oeste,predicao)

}
  colnames(aux)<- c(name[1:8])
  
  
aux<- aux %>% gather( "variaveis", "FLO", 2:8)

intercepto <- modelo_GAM_Centro_oeste$coefficients[1]
aux$FLO<- aux$FLO - intercepto
aux$crescimento = as.factor(ifelse(aux$FLO > 0, yes = 1, no = 0))

p_Centro_oeste1<- ggplot(data = aux, aes(x=  fct_reorder(variaveis, FLO, .desc = TRUE), y = FLO))+
  geom_col(aes(fill = crescimento))+
  labs(x = "", y = "Dias pré florescimento")+
 coord_flip()+
        geom_hline(yintercept = 0) +
  guides(fill = FALSE) +
  scale_fill_manual(values = c("firebrick", "dodgerblue4"))+
  theme_bw()
```


```{r}

Temporario<- Centro_oeste[,c(-1,-3)]


Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

Temporario1<- summary(modelo_GAM_Centro_oeste)
Temporario1<-data.frame(Temporario1[["p.coeff"]])
Temporario1<- data.frame("variaveis" = row.names(Temporario1), "estimativas" = Temporario1$Temporario1...p.coeff...)
Temporario1<- Temporario1[c(2:32),]
Temporario1$variaveis<-gsub("GENOTIPO", "", Temporario1$variaveis)

Temporario1$crescimento = as.factor(ifelse(Temporario1$estimativas > 0, yes = 1, no = 0))

p_Centro_oeste2<-ggplot(data = Temporario1, aes(x=  fct_reorder(variaveis, estimativas, .desc = TRUE), y = estimativas))+
  geom_col(aes(fill = crescimento))+
  labs(x = "", y = "Pre and post flowering days")+
 coord_flip()+
        geom_hline(yintercept = 0) +
  guides(fill = FALSE) +
  scale_fill_manual(values = c("firebrick", "dodgerblue4"))+
  theme_bw()


```



```{r}
#AA
Temporario1<- Temporario[Temporario$GENOTIPO %in% c("AA"),]
  media_Temporario1<- Temporario1 %>% group_by(GENOTIPO) %>% summarise(Tmin_V=mean(Tmin_V),   Tmin_ACC_V=mean(Tmin_ACC_V),  Tmin_R =mean(Tmin_R),    Tmax_Minima= mean(Tmax_Minima),   Tmin_ACC_R = mean(Tmin_ACC_R),  Rad_ACC=mean(Rad_ACC),   Graus_dia_FLO= mean(Graus_dia_FLO))
  
Tmin_V<-data.frame()
Tmin_V<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO", "Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_V["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmin_V["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_V["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_V["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_V["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_V["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_V["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_V)

Tmin_ACC_V<-data.frame()
Tmin_ACC_V<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_ACC_V["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_ACC_V["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_ACC_V["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_ACC_V["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_ACC_V["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_ACC_V["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_ACC_V["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_ACC_V)

Tmin_R<-data.frame()
Tmin_R<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_R["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmin_R["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_R["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_R["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_R["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_R["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_R["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_R)

Tmax_Minima<-data.frame()
Tmax_Minima<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmax_Minima["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmax_Minima["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmax_Minima["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmax_Minima["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmax_Minima["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmax_Minima["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmax_Minima["FLO"] = predict(modelo_GAM_Centro_oeste,Tmax_Minima)

Tmin_ACC_R<-data.frame()
Tmin_ACC_R<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_ACC_R["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmin_ACC_R["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_ACC_R["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_ACC_R["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_ACC_R["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_ACC_R["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_ACC_R["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_ACC_R)

Rad_ACC<-data.frame()
Rad_ACC<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Rad_ACC["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Rad_ACC["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Rad_ACC["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Rad_ACC["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Rad_ACC["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Rad_ACC["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Rad_ACC["FLO"] = predict(modelo_GAM_Centro_oeste,Rad_ACC)

Graus_dia_FLO<-data.frame()
Graus_dia_FLO<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Graus_dia_FLO["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Graus_dia_FLO["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Graus_dia_FLO["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Graus_dia_FLO["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Graus_dia_FLO["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Graus_dia_FLO["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Graus_dia_FLO["FLO"] = predict(modelo_GAM_Centro_oeste,Graus_dia_FLO)

a=Tmin_V
b=Tmin_ACC_V
c=Tmin_R
d=Tmax_Minima
e=Tmin_ACC_R
f=Rad_ACC
g=Graus_dia_FLO
  
intercepto <- modelo_GAM_Centro_oeste$coefficients[1]
a$crescimento = as.factor(ifelse(a$FLO > intercepto, yes = 1, no = 0))
b$crescimento = as.factor(ifelse(b$FLO > intercepto, yes = 1, no = 0))
c$crescimento = as.factor(ifelse(c$FLO > intercepto, yes = 1, no = 0))
d$crescimento = as.factor(ifelse(d$FLO > intercepto, yes = 1, no = 0))
e$crescimento = as.factor(ifelse(e$FLO > intercepto, yes = 1, no = 0))
f$crescimento = as.factor(ifelse(f$FLO > intercepto, yes = 1, no = 0))
g$crescimento = as.factor(ifelse(g$FLO > intercepto, yes = 1, no = 0))



test1<-ggplot(a, mapping = aes(x=Tmin_V, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura mínima no vegetativo (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test2<-ggplot(b, mapping = aes(x=Tmin_ACC_V, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura mínima acumulado no vegetativo (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test3<-ggplot(c, mapping = aes(x=Tmin_R, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura mínima no reprodutivo (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test4<-ggplot(d, mapping = aes(x=Tmax_Minima, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura máxima mínima (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test5<-ggplot(e, mapping = aes(x=Tmin_ACC_R, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura mínima acumulada no reprodutivo (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test6<-ggplot(f, mapping = aes(x=Rad_ACC, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Radiação acumulada (MJ/m²)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test7<-ggplot(g, mapping = aes(x=Graus_dia_FLO, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Graus-dia para o florescimento(ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")
#library(patchwork)
((p_Centro_oeste1/test3)|(test1/test7/test6)|(test4/test5/test2))+plot_annotation(tag_levels = 'A', tag_prefix = '(', tag_suffix = ')')


```



```{r}
#install.packages('mgcViz')



#library(mgcViz)
viz <- getViz(modelo_GAM_Centro_oeste)
trt<-plot(viz, allTerms = F) +
  l_ciPoly()+
    l_fitLine(colour = "blue") + l_rug(mapping = aes(x=x, y=y)) +
    geom_hline(yintercept = 0, linetype = 2, alpha=0.4)+
    theme_classic()
trt[["plots"]][[1]][["ggObj"]][["labels"]][["x"]]<-c("Tmax_min (ºC)")
trt[["plots"]][[1]][["ggObj"]][["labels"]][["title"]]<-c("(D)")

trt[["plots"]][[2]][["ggObj"]][["labels"]][["x"]]<-c("Tmin_ACC_R (ºC)")
trt[["plots"]][[2]][["ggObj"]][["labels"]][["title"]]<-c("(E)")

trt[["plots"]][[3]][["ggObj"]][["labels"]][["x"]]<-c("Rad_ACC (MJ/m²)")
trt[["plots"]][[3]][["ggObj"]][["labels"]][["title"]]<-c("(F)")

trt[["plots"]][[4]][["ggObj"]][["labels"]][["x"]]<-c("Gegree_day_FLO (ºC)")
trt[["plots"]][[4]][["ggObj"]][["labels"]][["title"]]<-c("(G)")


print(trt, pages = 1)


```
```{r}

```

```{r}
#install.packages("ggeffects")
#library(ggeffects)

mydf <- ggpredict(modelo_GAM_Centro_oeste, terms = "Tmin_R")
a<-ggplot(mydf, aes(x, predicted)) +
  geom_line(color = "blue") +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1)+
  labs(y = "Florescimento (DAE)",  x ="Tmin_R (ºC)", title = "(A)")+
  theme_classic()

mydf <- ggpredict(modelo_GAM_Centro_oeste, terms = "Tmin_V")
b<-ggplot(mydf, aes(x, predicted)) +
  geom_line(color = "blue") +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1)+
  labs(y = "Florescimento (DAE)",  x ="Tmin_V (ºC)", title = "(B)")+
  theme_classic()

mydf <- ggpredict(modelo_GAM_Centro_oeste, terms = "Tmin_ACC_V")
c<-ggplot(mydf, aes(x, predicted)) +
  geom_line(color = "blue") +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1)+
  labs(y = "Florescimento (DAE)",  x ="Tmin_ACC_V (ºC)", title = "(C)")+
  theme_classic()


a+b+c
```

```{r}
data.frame(trt[["plots"]][[3]][["ggObj"]][["data"]])
```

```{r}
library(patchwork)

((imp1+imp2+imp3)/(imp4+imp5))
```
# predicao

```{r}

Temporario<- Centro_oeste[,c(-1,-3)]


Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

Temporario1<- Temporario[Temporario$GENOTIPO %in% c("AA"),]
Temporario1<- Temporario1 %>%  select(GENOTIPO,Tmin_V,   Tmin_ACC_V,  Tmin_R ,    Tmax_Minima,   Tmin_ACC_R ,  Rad_ACC,   Graus_dia_FLO)


media_Temporario1<- Temporario1 %>% group_by(GENOTIPO) %>% summarise(Tmin_V=mean(Tmin_V),   Tmin_ACC_V=mean(Tmin_ACC_V),  Tmin_R =mean(Tmin_R),    Tmax_Minima= mean(Tmax_Minima),   Tmin_ACC_R = mean(Tmin_ACC_R),  Rad_ACC=mean(Rad_ACC),   Graus_dia_FLO= mean(Graus_dia_FLO))
aux<-data.frame()
aux[1,1]<- media_Temporario1[1,1]

name<-colnames(media_Temporario1)
for (i in 2:8) {
 Temporario2<- vector()
Temporario2[1]<- c(media_Temporario1[i]+(media_Temporario1[i]*0.10))
Temporario2[2]<- c(media_Temporario1[i]-(media_Temporario1[i]*0.10))

  Temporario3<-  Temporario1[Temporario1[i]<=Temporario2[1],]
  Temporario3<-  Temporario3[Temporario3[i]>=Temporario2[2],]
  predicao<- c(apply(Temporario3[,-1],2,mean))

  predicao<- data.frame(t(predicao))
  
  predicao[i-1] <- media_Temporario1[i]
  predicao["GENOTIPO"]<- c("AA")
  aux[1,i] = predict(modelo_GAM_Centro_oeste,predicao)

}
  colnames(aux)<- c(name[1:8])
  
  
aux<- aux %>% gather( "variaveis", "FLO", 2:8)

intercepto <- modelo_GAM_Centro_oeste$coefficients[1]
aux$FLO<- aux$FLO - intercepto
aux$crescimento = as.factor(ifelse(aux$FLO > 0, yes = 1, no = 0))

p_Centro_oeste1<- ggplot(data = aux, aes(x=  fct_reorder(variaveis, FLO, .desc = TRUE), y = FLO))+
  geom_col(aes(fill = crescimento))+
  labs(x = "", y = "Dias pré florescimento")+
 coord_flip()+
        geom_hline(yintercept = 0) +
  guides(fill = FALSE) +
  scale_fill_manual(values = c("firebrick", "dodgerblue4"))+
  theme_bw()
```

```{r}
#AA
Temporario1<- Temporario[Temporario$GENOTIPO %in% c("AA"),]
  media_Temporario1<- Temporario1 %>% group_by(GENOTIPO) %>% summarise(Tmin_V=mean(Tmin_V),   Tmin_ACC_V=mean(Tmin_ACC_V),  Tmin_R =mean(Tmin_R),    Tmax_Minima= mean(Tmax_Minima),   Tmin_ACC_R = mean(Tmin_ACC_R),  Rad_ACC=mean(Rad_ACC),   Graus_dia_FLO= mean(Graus_dia_FLO))
  
  Temporario1<- Temporario1 %>%  select(GENOTIPO, Tmin_V,   Tmin_ACC_V,  Tmin_R,    Tmax_Minima,   Tmin_ACC_R,  Rad_ACC,   Graus_dia_FLO)


Temporario2<- vector()
Temporario2[1]<- c(media_Temporario1$Tmin_V+(media_Temporario1$Tmin_V*0.10))
Temporario2[2]<- c(media_Temporario1$Tmin_V-(media_Temporario1$Tmin_V*0.10))

  Temporario3<-  Temporario1[Temporario1$Tmin_V<=Temporario2[1],]
  Temporario3<-  Temporario3[Temporario3$Tmin_V>=Temporario2[2],]
  predicao<- c(apply(Temporario3[,-1],2,mean))

  predicao<- data.frame(t(predicao))
  
  predicao$Tmin_V<- media_Temporario1$Tmin_V
  predicao["GENOTIPO"]<- c("AA")
  
Tmin_V<-data.frame()
Tmin_V<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO", "Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_V["Tmin_ACC_V"]<- c(predicao$Tmin_ACC_V)
Tmin_V["Tmin_R"]<- c(predicao$Tmin_R)
Tmin_V["Tmax_Minima"]<- c(predicao$Tmax_Minima)
Tmin_V["Tmin_ACC_R"]<- c(predicao$Tmin_ACC_R)
Tmin_V["Rad_ACC"]<- c(predicao$Rad_ACC)
Tmin_V["Graus_dia_FLO"]<- c(predicao$Graus_dia_FLO)
Tmin_V["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_V)


Temporario2<- vector()
Temporario2[1]<- c(media_Temporario1$Tmin_ACC_V+(media_Temporario1$Tmin_ACC_V*0.10))
Temporario2[2]<- c(media_Temporario1$Tmin_ACC_V-(media_Temporario1$Tmin_ACC_V*0.10))

  Temporario3<-  Temporario1[Temporario1$Tmin_ACC_V<=Temporario2[1],]
  Temporario3<-  Temporario3[Temporario3$Tmin_ACC_V>=Temporario2[2],]
  predicao<- c(apply(Temporario3[,-1],2,mean))

  predicao<- data.frame(t(predicao))
  
  predicao$Tmin_ACC_V <- media_Temporario1$Tmin_ACC_V
  predicao["GENOTIPO"]<- c("AA")

Tmin_ACC_V<-data.frame()
Tmin_ACC_V<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_ACC_V["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_ACC_V["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_ACC_V["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_ACC_V["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_ACC_V["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_ACC_V["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_ACC_V["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_ACC_V)


Temporario2<- vector()
Temporario2[1]<- c(media_Temporario1$Tmin_R+(media_Temporario1$Tmin_R*0.10))
Temporario2[2]<- c(media_Temporario1$Tmin_R-(media_Temporario1$Tmin_R*0.10))

  Temporario3<-  Temporario1[Temporario1$Tmin_R<=Temporario2[1],]
  Temporario3<-  Temporario3[Temporario3$Tmin_R>=Temporario2[2],]
  predicao<- c(apply(Temporario3[,-1],2,mean))

  predicao<- data.frame(t(predicao))
  
  predicao$Tmin_R <- media_Temporario1$Tmin_R
  predicao["GENOTIPO"]<- c("AA")

Tmin_R<-data.frame()
Tmin_R<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_R["Tmin_ACC_V"]<- c(predicao$Tmin_ACC_V)
Tmin_R["Tmin_V"]<- c(predicao$Tmin_V)
Tmin_R["Tmax_Minima"]<- c(predicao$Tmax_Minima)
Tmin_R["Tmin_ACC_R"]<- c(predicao$Tmin_ACC_R)
Tmin_R["Rad_ACC"]<- c(predicao$Rad_ACC)
Tmin_R["Graus_dia_FLO"]<- c(predicao$Graus_dia_FLO)
Tmin_R["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_R)

Temporario2<- vector()
Temporario2[1]<- c(media_Temporario1$Tmax_Minima+(media_Temporario1$Tmax_Minima*0.10))
Temporario2[2]<- c(media_Temporario1$Tmax_Minima-(media_Temporario1$Tmax_Minima*0.10))

  Temporario3<-  Temporario1[Temporario1$Tmax_Minima<=Temporario2[1],]
  Temporario3<-  Temporario3[Temporario3$Tmax_Minima>=Temporario2[2],]
  predicao<- c(apply(Temporario3[,-1],2,mean))

  predicao<- data.frame(t(predicao))
  
  predicao$Tmax_Minima <- media_Temporario1$Tmax_Minima
  predicao["GENOTIPO"]<- c("AA")

Tmax_Minima<-data.frame()
Tmax_Minima<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmax_Minima["Tmin_ACC_V"]<- c(predicao$Tmin_ACC_V)
Tmax_Minima["Tmin_V"]<- c(predicao$Tmin_V)
Tmax_Minima["Tmin_R"]<- c(predicao$Tmin_R)
Tmax_Minima["Tmin_ACC_R"]<- c(predicao$Tmin_ACC_R)
Tmax_Minima["Rad_ACC"]<- c(predicao$Rad_ACC)
Tmax_Minima["Graus_dia_FLO"]<- c(predicao$Graus_dia_FLO)
Tmax_Minima["FLO"] = predict(modelo_GAM_Centro_oeste,Tmax_Minima)

Temporario2<- vector()
Temporario2[1]<- c(media_Temporario1$Tmin_ACC_R+(media_Temporario1$Tmin_ACC_R*0.10))
Temporario2[2]<- c(media_Temporario1$Tmin_ACC_R-(media_Temporario1$Tmin_ACC_R*0.10))

  Temporario3<-  Temporario1[Temporario1$Tmin_ACC_R<=Temporario2[1],]
  Temporario3<-  Temporario3[Temporario3$Tmin_ACC_R>=Temporario2[2],]
  predicao<- c(apply(Temporario3[,-1],2,mean))

  predicao<- data.frame(t(predicao))
  
  predicao$Tmin_ACC_R <- media_Temporario1$Tmin_ACC_R
  predicao["GENOTIPO"]<- c("AA")


Tmin_ACC_R<-data.frame()
Tmin_ACC_R<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_ACC_R["Tmin_ACC_V"]<- c(predicao$Tmin_ACC_V)
Tmin_ACC_R["Tmin_V"]<- c(predicao$Tmin_V)
Tmin_ACC_R["Tmax_Minima"]<- c(predicao$Tmax_Minima)
Tmin_ACC_R["Tmin_R"]<- c(predicao$Tmin_R)
Tmin_ACC_R["Rad_ACC"]<- c(predicao$Rad_ACC)
Tmin_ACC_R["Graus_dia_FLO"]<- c(predicao$Graus_dia_FLO)
Tmin_ACC_R["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_ACC_R)


Temporario2<- vector()
Temporario2[1]<- c(media_Temporario1$Rad_ACC+(media_Temporario1$Rad_ACC*0.10))
Temporario2[2]<- c(media_Temporario1$Rad_ACC-(media_Temporario1$Rad_ACC*0.10))

  Temporario3<-  Temporario1[Temporario1$Rad_ACC<=Temporario2[1],]
  Temporario3<-  Temporario3[Temporario3$Rad_ACC>=Temporario2[2],]
  predicao<- c(apply(Temporario3[,-1],2,mean))

  predicao<- data.frame(t(predicao))
  
  predicao$Rad_ACC <- media_Temporario1$Rad_ACC
  predicao["GENOTIPO"]<- c("AA")
  

Rad_ACC<-data.frame()
Rad_ACC<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Rad_ACC["Tmin_ACC_V"]<- c(predicao$Tmin_ACC_V)
Rad_ACC["Tmin_V"]<- c(predicao$Tmin_V)
Rad_ACC["Tmax_Minima"]<- c(predicao$Tmax_Minima)
Rad_ACC["Tmin_ACC_R"]<- c(predicao$Tmin_ACC_R)
Rad_ACC["Tmin_R"]<- c(predicao$Tmin_R)
Rad_ACC["Graus_dia_FLO"]<- c(predicao$Graus_dia_FLO)
Rad_ACC["FLO"] = predict(modelo_GAM_Centro_oeste,Rad_ACC)

Temporario2<- vector()
Temporario2[1]<- c(media_Temporario1$Graus_dia_FLO+(media_Temporario1$Graus_dia_FLO*0.10))
Temporario2[2]<- c(media_Temporario1$Graus_dia_FLO-(media_Temporario1$Graus_dia_FLO*0.10))

  Temporario3<-  Temporario1[Temporario1$Graus_dia_FLO<=Temporario2[1],]
  Temporario3<-  Temporario3[Temporario3$Graus_dia_FLO>=Temporario2[2],]
  predicao<- c(apply(Temporario3[,-1],2,mean))

  predicao<- data.frame(t(predicao))
  
  predicao$Graus_dia_FLO <- media_Temporario1$Graus_dia_FLO
  predicao["GENOTIPO"]<- c("AA")
  

Graus_dia_FLO<-data.frame()
Graus_dia_FLO<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Graus_dia_FLO["Tmin_ACC_V"]<- c(predicao$Tmin_ACC_V)
Graus_dia_FLO["Tmin_V"]<- c(predicao$Tmin_V)
Graus_dia_FLO["Tmax_Minima"]<- c(predicao$Tmax_Minima)
Graus_dia_FLO["Tmin_ACC_R"]<- c(predicao$Tmin_ACC_R)
Graus_dia_FLO["Tmin_R"]<- c(predicao$Tmin_R)
Graus_dia_FLO["Rad_ACC"]<- c(predicao$Rad_ACC)
Graus_dia_FLO["FLO"] = predict(modelo_GAM_Centro_oeste,Graus_dia_FLO)

a=Tmin_V
b=Tmin_ACC_V
c=Tmin_R
d=Tmax_Minima
e=Tmin_ACC_R
f=Rad_ACC
g=Graus_dia_FLO
  
intercepto <- modelo_GAM_Centro_oeste$coefficients[1]
a$crescimento = as.factor(ifelse(a$FLO > intercepto, yes = 1, no = 0))
b$crescimento = as.factor(ifelse(b$FLO > intercepto, yes = 1, no = 0))
c$crescimento = as.factor(ifelse(c$FLO > intercepto, yes = 1, no = 0))
d$crescimento = as.factor(ifelse(d$FLO > intercepto, yes = 1, no = 0))
e$crescimento = as.factor(ifelse(e$FLO > intercepto, yes = 1, no = 0))
f$crescimento = as.factor(ifelse(f$FLO > intercepto, yes = 1, no = 0))
g$crescimento = as.factor(ifelse(g$FLO > intercepto, yes = 1, no = 0))



test1<-ggplot(a, mapping = aes(x=Tmin_V, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura mínima no vegetativo (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test2<-ggplot(b, mapping = aes(x=Tmin_ACC_V, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura mínima acumulado no vegetativo (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test3<-ggplot(c, mapping = aes(x=Tmin_R, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura mínima no reprodutivo (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test4<-ggplot(d, mapping = aes(x=Tmax_Minima, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura máxima mínima (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test5<-ggplot(e, mapping = aes(x=Tmin_ACC_R, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Temperatura mínima acumulada no reprodutivo (ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test6<-ggplot(f, mapping = aes(x=Rad_ACC, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Radiação acumulada (MJ/m²)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test7<-ggplot(g, mapping = aes(x=Graus_dia_FLO, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Graus-dia para o florescimento(ºC)" , y="Florescimento (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")
#library(patchwork)
((p_Centro_oeste1/test3)|(test1/test7/test6)|(test4/test5/test2))+plot_annotation(tag_levels = 'A', tag_prefix = '(', tag_suffix = ')')


```


# predicao 2



```{r}

Temporario<- Centro_oeste[,c(-1,-3)]


Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

media_FLO<- mean(Temporario$FLO_M)

teste <-Temporario$FLO_M[Temporario$FLO_M >= 85.5 & Temporario$FLO_M <= 94.5]

dados_teste <- Temporario[Temporario$FLO_M %in% teste,]

Temporario1<- dados_teste[dados_teste$GENOTIPO %in% c("AA"),]
media_Temporario1<- Temporario1 %>% group_by(GENOTIPO) %>% summarise(Tmin_V=mean(Tmin_V),   Tmin_ACC_V=mean(Tmin_ACC_V),  Tmin_R =mean(Tmin_R),    Tmax_Minima= mean(Tmax_Minima),   Tmin_ACC_R = mean(Tmin_ACC_R),  Rad_ACC=mean(Rad_ACC),   Graus_dia_FLO= mean(Graus_dia_FLO))
aux<-data.frame()
aux[1,1]<- media_Temporario1[1,1]

name<-colnames(media_Temporario1)
for (i in 2:ncol(media_Temporario1)) {
  predicao<-media_Temporario1
  predicao<-predicao %>% mutate(predicao[i], predicao[i]+(predicao[i]*0.10))
  aux[1,i] = predict(modelo_GAM_Centro_oeste,predicao)

}
  colnames(aux)<- c(colnames(media_Temporario1))
  
  
aux<- aux %>% gather( "variaveis", "FLO", 2:ncol(media_Temporario1))

aux$FLO<- aux$FLO - media_FLO
aux$crescimento = as.factor(ifelse(aux$FLO > 0, yes = 1, no = 0))

aux2<-data.frame()
aux2[1,1]<- media_Temporario1[1,1]

name<-colnames(media_Temporario1)
for (i in 2:ncol(media_Temporario1)) {
  predicao<-media_Temporario1
  predicao<-predicao %>% mutate(predicao[i], predicao[i]-(predicao[i]*0.10))
  aux2[1,i] = predict(modelo_GAM_Centro_oeste,predicao) 

}

  colnames(aux2)<- c(colnames(media_Temporario1))
  
aux2<- aux2 %>% gather( "variaveis", "FLO", 2:ncol(media_Temporario1))

aux2$FLO<- aux2$FLO - media_FLO
aux2$crescimento = as.factor(ifelse(aux2$FLO > 0, yes = 1, no = 0))



aux2$tipo<- c("Menos")
aux$tipo<- c("Mais")



p_Centro_oeste1<- ggplot()+ 
  geom_col_pattern(data = aux2, aes(x=  fct_reorder(variaveis, aux$FLO, .desc = TRUE), y = FLO, fill = crescimento, pattern =tipo), alpha=0.5, linetype = 2,
           color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6)+
  geom_col(data = aux, aes(x=  fct_reorder(variaveis, FLO, .desc = TRUE), y = FLO, fill = crescimento , pattern =tipo))+
  geom_col_pattern(aes(x=  c(aux2[4,2]), y = aux2[4,3], fill =aux2[4,4]),alpha=0.5, linetype = 2,
           color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6)+
 coord_flip()+
        geom_hline(yintercept = 0) +
  scale_pattern_manual(values = c(Menos = "stripe", Mais = "none"), labels=c("+10%", "-10%"))+
  labs(x = "",y = "Dias pré e pós florescimento", pattern = "Média modificada em:") + 
  guides(pattern = guide_legend(override.aes = list(fill = "white")), fill = "none")+
  scale_fill_manual(values = c("firebrick", "dodgerblue4"))+
    theme_bw()+
   theme(legend.position="bottom")
```


```{r}
Temporario<- Centro_oeste[,c(-1,-3)]


Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67")

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

media_FLO<- mean(Temporario$FLO_M)

teste <-Temporario$FLO_M[Temporario$FLO_M >= 85.5 & Temporario$FLO_M <= 94.5]

dados_teste <- Temporario[Temporario$FLO_M %in% teste,]

Temporario1<- dados_teste[dados_teste$GENOTIPO %in% c("AA"),]
media_Temporario1<- Temporario1 %>% group_by(GENOTIPO) %>% summarise(Tmin_V=mean(Tmin_V),   Tmin_ACC_V=mean(Tmin_ACC_V),  Tmin_R =mean(Tmin_R),    Tmax_Minima= mean(Tmax_Minima),   Tmin_ACC_R = mean(Tmin_ACC_R),  Rad_ACC=mean(Rad_ACC),   Graus_dia_FLO= mean(Graus_dia_FLO))
aux<-data.frame()
aux[1,1]<- media_Temporario1[1,1]

name<-colnames(media_Temporario1)
for (i in 2:ncol(media_Temporario1)) {
  predicao<-media_Temporario1
  predicao<-predicao %>% mutate(predicao[i], predicao[i]+1)
  aux[1,i] = predict(modelo_GAM_Centro_oeste,predicao)

}
  colnames(aux)<- c(colnames(media_Temporario1))
  
  
aux<- aux %>% gather( "variaveis", "FLO", 2:ncol(media_Temporario1))

aux$FLO<- aux$FLO - media_FLO
aux$crescimento = as.factor(ifelse(aux$FLO > 0, yes = 1, no = 0))
```




```{r}
#AA
Temporario1<- Temporario[Temporario$GENOTIPO %in% c("AA"),]
  media_Temporario1<- Temporario1 %>% group_by(GENOTIPO) %>% summarise(Tmin_V=mean(Tmin_V),   Tmin_ACC_V=mean(Tmin_ACC_V),  Tmin_R =mean(Tmin_R),    Tmax_Minima= mean(Tmax_Minima),   Tmin_ACC_R = mean(Tmin_ACC_R),  Rad_ACC=mean(Rad_ACC),   Graus_dia_FLO= mean(Graus_dia_FLO))
  
Tmin_V<-data.frame()
Tmin_V<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO", "Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_V["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmin_V["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_V["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_V["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_V["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_V["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_V["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_V)

Tmin_ACC_V<-data.frame()
Tmin_ACC_V<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_ACC_V["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_ACC_V["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_ACC_V["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_ACC_V["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_ACC_V["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_ACC_V["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_ACC_V["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_ACC_V)

Tmin_R<-data.frame()
Tmin_R<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_R["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmin_R["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_R["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_R["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_R["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_R["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_R["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_R)

Tmax_Minima<-data.frame()
Tmax_Minima<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmax_Minima["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmax_Minima["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmax_Minima["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmax_Minima["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmax_Minima["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmax_Minima["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmax_Minima["FLO"] = predict(modelo_GAM_Centro_oeste,Tmax_Minima)

Tmin_ACC_R<-data.frame()
Tmin_ACC_R<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_ACC_R["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmin_ACC_R["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_ACC_R["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_ACC_R["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_ACC_R["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_ACC_R["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_ACC_R["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_ACC_R)

Rad_ACC<-data.frame()
Rad_ACC<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Rad_ACC["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Rad_ACC["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Rad_ACC["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Rad_ACC["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Rad_ACC["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Rad_ACC["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Rad_ACC["FLO"] = predict(modelo_GAM_Centro_oeste,Rad_ACC)

Graus_dia_FLO<-data.frame()
Graus_dia_FLO<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Graus_dia_FLO["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Graus_dia_FLO["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Graus_dia_FLO["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Graus_dia_FLO["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Graus_dia_FLO["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Graus_dia_FLO["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Graus_dia_FLO["FLO"] = predict(modelo_GAM_Centro_oeste,Graus_dia_FLO)

a=Tmin_V
b=Tmin_ACC_V
c=Tmin_R
d=Tmax_Minima
e=Tmin_ACC_R
f=Rad_ACC
g=Graus_dia_FLO
  
intercepto <- media_FLO
a$crescimento = as.factor(ifelse(a$FLO > intercepto, yes = 1, no = 0))
b$crescimento = as.factor(ifelse(b$FLO > intercepto, yes = 1, no = 0))
c$crescimento = as.factor(ifelse(c$FLO > intercepto, yes = 1, no = 0))
d$crescimento = as.factor(ifelse(d$FLO > intercepto, yes = 1, no = 0))
e$crescimento = as.factor(ifelse(e$FLO > intercepto, yes = 1, no = 0))
f$crescimento = as.factor(ifelse(f$FLO > intercepto, yes = 1, no = 0))
g$crescimento = as.factor(ifelse(g$FLO > intercepto, yes = 1, no = 0))



test1<-ggplot(a, mapping = aes(x=Tmin_V, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmin_V (ºC)" , y="Flowering (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test2<-ggplot(b, mapping = aes(x=Tmin_ACC_V, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmin_ACC_V (ºC)" , y="Flowering (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test3<-ggplot(c, mapping = aes(x=Tmin_R, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmin_R (ºC)" , y="Flowering (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test4<-ggplot(d, mapping = aes(x=Tmax_Minima, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmax_Min (ºC)" , y="Flowering (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test5<-ggplot(e, mapping = aes(x=Tmin_ACC_R, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmin_ACC_R (ºC)" , y="Flowering (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test6<-ggplot(f, mapping = aes(x=Rad_ACC, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Rad_ACC (MJ/m²)" , y="Flowering (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test7<-ggplot(g, mapping = aes(x=Graus_dia_FLO, y=FLO))+
  geom_point( mapping =aes(color = crescimento))+
  geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Degree_days_FLO (ºC)" , y="Flowering (DAE)")+
  guides(fill = FALSE) +
  scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")
#library(patchwork)
((test1|test7|test6|test3)/(test4|test5|test2))+plot_annotation(tag_levels = 'A', tag_prefix = '(', tag_suffix = ')')


```



