---
title: "Figura 11"
author: "Gutemberg Resende Honorio Filho"
date: "07/01/2022"
output: html_document
---


OBS.: Esse arquivo é uma cópia do arquivo "validação cruzada".



# PACOTES

```{r}
library(tidyverse)
library(mgcv)
library(caTools)
library(patchwork)
```

# DADOS


```{r Diretório} 


# DIRETÓRIO DOS DADOS 

Tabelabruta<- read.csv("d:/Users/Cristiane Resende/Desktop/Gutemberg Honorio/Mestrado/Repositorio_4/Analise_e_modelagem_Arroz/Merge_1980_2018.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE) # tabela com os dados originais

# criando coluna com macrorregiões

Tabelabruta<- mutate(Tabelabruta,REGIAO = case_when(UF == 'GO'| UF == 'DF' |UF == 'MS' | UF == 'MT' ~ 'Centro-Oeste',
                              UF == 'AL'| UF == 'BA' |UF == 'CE' | UF == 'MA' | UF == 'PB' | UF == 'PE' | UF == 'PI' | UF == 'RN' | UF == 'SE' ~ 'Nordeste',
                              UF == 'AC' | UF == 'AM' | UF == 'AP' | UF == 'PA' | UF == 'RO' | UF == 'RR' | UF == 'TO' ~ 'Norte',
                              UF == 'ES' | UF == 'MG' | UF == 'SP' | UF == 'RJ' ~ 'Sudeste',
                              UF == 'RS' | UF == 'SC' | UF == 'PR' ~ 'Sul'))

# Tabelas acessório

TabelabrutaIRR = subset(Tabelabruta, SIST_CULT == "IRRIGATED") # Somente Irrigado
TabelabrutaTA = subset(Tabelabruta, SIST_CULT == "UPLAND") # Somente Terras altas

# Filtrando os dados


IRR<-TabelabrutaIRR %>% mutate(UR_Media=(umidade_Media),UR_V=	(umidade_V), UR_fld_m=	(umidade_fld_m),	UR_R=	(umidade_R), Graus_dia_ciclo=(graus_dia_ciclo), Graus_dia_FLO=(graus_dia_FLO+graus_dia_IP))

IRR <- select(IRR,latitude, longitude, GENOTIPO, ID_ENSAIO,ano, Altitude, REGIAO, UF, FLO_E, Tmax_Maxima ,Tmax_fld_m ,	Tmax_R,	Tmax_ACC_R, Tmax_Minima,	Tmax_Media,Tmax_V ,Tmax_ACC_V,	Tmin_Maxima,Tmin_Minima ,	Tmin_Media ,	Tmin_V ,	Tmin_ACC_V , Tmin_fld_m ,	Tmin_R,	Tmin_ACC_R , Chuva_ACC ,	Chuva_ACC_V, Chuva_ACC_R, Rad_ACC_R ,	Rad_ACC ,	Rad_ACC_V, UR_Media, UR_V, UR_fld_m,	UR_R, Graus_dia_ciclo, Graus_dia_FLO, ano)


#rm(TabelabrutaIRR,TabelabrutaTA,Tabelabruta)

# Removendo os genótipos que não serão estudados

IRR = IRR[IRR$GENOTIPO %in% c("ALIANCA",	"AVAXI CL",	"BR IRGA 409",	"BR IRGA 410",	"BR IRGA 412",	"BR IRGA 414",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS A704",	"BRS ALVORADA",	"BRS BIGUA",	"BRS CATIANA",	"BRS CIRAD 302",	"BRS FORMOSO",	"BRS FRONTEIRA",	"BRS GUARA",	"BRS JABURU",	"BRS JACANA",	"BRS PAMPA",	"BRS PAMPEIRA",	"BRS PELOTA",	"BRS QUERENCIA",	"BRS SINUELO CL",	"BRS TROPICAL",	"BRSMG RUBELITA",	"CICA 8",	"CT8452",	"DIAMANTE",	"EEA34",	"EMPASC 101",	"EMPASC 102",	"EPAGRI 108",	"EPAGRI 109",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"H6",	"H7 CL",	"IAC1289",	"IAC1298",	"IAC1299",	"IAC1307",	"IAC1311",	"IAPAR 58",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 428",	"IRGA 429",	"IRGA 430",	"IRGA97-05",	"IRGA97-10",	"IRGA97-11",	"IRGA97-28",	"JAVAE",	"JEQUITIBA",	"MARAJO",	"METICA 1",	"MOXOTO",	"OUROMINAS",	"PR267",	"PR268",	"PR306",	"PR331",	"PR349",	"PR380",	"PR498",	"PR631",	"PR67",	"PUITA INTA CL",	"RORAIMA",	"SAO FRANCISCO",	"SC138",	"SC173",	"SC237",	"SC240",	"SC250",	"SCS 112",	"SCS 114 ANDOSAN",	"SCS 116 SATORU",	"SCS 121 CL",	"SCSBRS 111",	"SCSBRS 113 TIO TAKA",	"SCSBRS PIRACEMA",	"SG11551",	"URUCUI"),]
IRR = IRR[IRR$UF!="MT",]

# Filtrando e gerando médias

IRR_Medio<- IRR %>% group_by(ID_ENSAIO, GENOTIPO, REGIAO) %>% summarise(  FLO_M= mean(FLO_E),  latitude= mean(latitude), longitude = mean(longitude), Altitude = mean(Altitude), Tmax_Maxima = mean(Tmax_Maxima) ,Tmax_fld_m = mean(Tmax_fld_m ),	Tmax_R= mean( Tmax_R),	Tmax_ACC_R= mean(Tmax_ACC_R ), Tmax_Minima= mean(Tmax_Minima ),	Tmax_Media= mean( Tmax_Media),Tmax_V = mean(Tmax_V ),Tmax_ACC_V= mean(Tmax_ACC_V ),	Tmin_Maxima= mean(Tmin_Maxima ),Tmin_Minima = mean(Tmin_Minima ),	Tmin_Media = mean(Tmin_Media ),	Tmin_V = mean(Tmin_V ),	Tmin_ACC_V = mean(Tmin_ACC_V ), Tmin_fld_m = mean( Tmin_fld_m),	Tmin_R= mean(Tmin_R ),	Tmin_ACC_R = mean(Tmin_ACC_R ), Chuva_ACC = mean(Chuva_ACC ),	Chuva_ACC_V= mean(Chuva_ACC_V ), Chuva_ACC_R= mean(Chuva_ACC_R ), Rad_ACC_R = mean(Rad_ACC_R ),	Rad_ACC = mean(Rad_ACC ),	Rad_ACC_V= mean(Rad_ACC_V ), UR_Media= mean( UR_Media), UR_V= mean( UR_V), UR_fld_m= mean(UR_fld_m ),	UR_R= mean(UR_R ), Graus_dia_ciclo= mean(Graus_dia_ciclo ), Graus_dia_FLO= mean(Graus_dia_FLO ))



# separando por macrorregião

Centro_oeste<- subset(IRR_Medio, (REGIAO == "Centro-Oeste")) # filtrando por região
Norte<- subset(IRR_Medio, (REGIAO == "Norte")) # filtrando por região
Nordeste<- subset(IRR_Medio, (REGIAO == "Nordeste")) # filtrando por região
Sul<- subset(IRR_Medio, (REGIAO == "Sul")) # filtrando por região
Sudeste<- subset(IRR_Medio, (REGIAO == "Sudeste")) # filtrando por região

```
# VALIDAÇÃO CRUZADA

## CENTRO-OESTE
### LM
```{r}
res_Centro_oeste_LM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Centro_oeste$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Centro_oeste$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Centro_oeste[Centro_oeste$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Centro_oeste[Centro_oeste$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409", "BR IRGA 410",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS CIRAD 302",	"BRS FRONTEIRA",	"BRS JACANA",	"BRS PAMPA",	"BRS PELOTA",	"BRS SINUELO CL",	"EMPASC 102",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"IAC1289",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 429",	"IRGA97-11",	"IRGA97-28",	"JEQUITIBA",	"PR306",	"PR349",	"PR498",	"PR631",	"SC240",	"SC250", "PR67","SCSBRS 111", "IAPAR 58", "SC237", "URUCUI" )

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = lm(FLO_M~ GENOTIPO + longitude + Tmax_Maxima + Tmax_fld_m + Tmax_R + 
    Tmax_ACC_R + Tmax_Minima + Tmax_V + Tmax_ACC_V + Tmin_Maxima + 
    Tmin_Minima + Tmin_Media + Tmin_ACC_V + Tmin_fld_m + Tmin_R + 
    Tmin_ACC_R + Chuva_ACC_V , data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409", "BR IRGA 410",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS CIRAD 302",	"BRS FRONTEIRA",	"BRS JACANA",	"BRS PAMPA",	"BRS PELOTA",	"BRS SINUELO CL",	"EMPASC 102",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"IAC1289",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 429",	"IRGA97-11",	"IRGA97-28",	"JEQUITIBA",	"PR306",	"PR349",	"PR498",	"PR631",	"SC240",	"SC250", "PR67","SCSBRS 111", "IAPAR 58", "SC237", "URUCUI" )

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Centro_oeste_LM[i] = mean(abs(predicao$FLO_M - aux) )
#print(i)
}
```

###GAM

```{r}
res_Centro_oeste_GAM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Centro_oeste$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Centro_oeste$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Centro_oeste[Centro_oeste$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Centro_oeste[Centro_oeste$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}
Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67"
)

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = gam(FLO_M~GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) +  s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67"
)

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Centro_oeste_GAM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```
### Erro
```{r}
GAM<- data.frame("Erro" = res_Centro_oeste_GAM, "Modelo" = "GAM")
LM<- data.frame("Erro" = res_Centro_oeste_LM, "Modelo" = "LM")


val<- data.frame()
val<- data.frame("Erro" = c(LM$Erro,GAM$Erro), "Modelo" = c(LM$Modelo,GAM$Modelo) )

v1<- ggplot(data = val, aes(y = Erro, x= Modelo, color=Modelo, fill = Modelo )) +
   geom_boxplot(
    width = .2, fill = "white",
    size = 1.5, outlier.shape = NA
  ) +
  ggdist::stat_halfeye(
    adjust = .60, 
    width = .55, 
    color = NA, 
    position = position_nudge(x = .14)
  ) +
  geom_point(
    position = position_nudge(x = -.22),
    shape = 95, size = 12, alpha = .25
  )+
  labs(y= "Average absolute error (days)", x="")+
  guides(color=FALSE)+
  scale_color_viridis_d()+
   scale_fill_viridis_d()+
   theme_classic(base_size = 12)+
 theme(legend.position="none")

```



## NORTE

### LM
```{r}
res_Norte_LM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Norte$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Norte$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Norte[Norte$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Norte[Norte$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409", "BR IRGA 412",	"BRS 7 TAIM",	"BRS BIGUA",	"BRS FRONTEIRA",	"BRS JACANA",	"BRS PELOTA",	"BRS TROPICAL",	"BRSMG RUBELITA",	"DIAMANTE",	"EPAGRI 108",	"EPAGRI 109",	"IRGA 424 RI",	"IRGA 425",	"IRGA 428",	"IRGA 429",	"PR306",	"RORAIMA",	"SC173",	"SC237",	"SC250",	"SCS 112",	"SCS 114 ANDOSAN",	"SCS 116 SATORU",	"SCSBRS 111",	"SCSBRS PIRACEMA","URUCUI","JEQUITIBA","PR349","PR67","SC240","IAC1289","SCS 121 CL")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = lm(log(FLO_M) ~ GENOTIPO + longitude + Altitude + Tmax_Maxima + 
    Tmax_R + Tmax_ACC_R + Tmin_V + Tmin_ACC_V + Tmin_R + Tmin_ACC_R + 
    Rad_ACC + Rad_ACC_V + UR_Media + UR_R + Graus_dia_ciclo + 
    Graus_dia_FLO  , data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409", "BR IRGA 412",	"BRS 7 TAIM",	"BRS BIGUA",	"BRS FRONTEIRA",	"BRS JACANA",	"BRS PELOTA",	"BRS TROPICAL",	"BRSMG RUBELITA",	"DIAMANTE",	"EPAGRI 108",	"EPAGRI 109",	"IRGA 424 RI",	"IRGA 425",	"IRGA 428",	"IRGA 429",	"PR306",	"RORAIMA",	"SC173",	"SC237",	"SC250",	"SCS 112",	"SCS 114 ANDOSAN",	"SCS 116 SATORU",	"SCSBRS 111",	"SCSBRS PIRACEMA","URUCUI","JEQUITIBA","PR349","PR67","SC240","IAC1289","SCS 121 CL")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Norte_LM[i] = mean(abs(predicao$FLO_M - exp(aux)))
print(i)
}
```
### GAM
```{r}
res_Norte_GAM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Norte$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Norte$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Norte[Norte$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Norte[Norte$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409","BR IRGA 412",	"BRS 7 TAIM",	"BRS A702 CL",	"BRS BIGUA",	"BRS FRONTEIRA",	"BRS JABURU",	"BRS JACANA",	"BRS PELOTA",	"BRS TROPICAL",	"BRSMG RUBELITA",	"DIAMANTE",	"EPAGRI 108",	"EPAGRI 109",	"IRGA 424 RI",	"IRGA 425",	"IRGA 428",	"IRGA 429",	"JEQUITIBA",	"PR306",	"PR349",	"PUITA INTA CL",	"RORAIMA",	"SC173",	"SC237",	"SC240",	"SC250",	"SCS 112",	"SCS 114 ANDOSAN",	"SCS 116 SATORU",	"SCS 121 CL",	"SCSBRS 111",	"SCSBRS PIRACEMA",	"URUCUI", "PR67", "IAC1289")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = gam(FLO_M ~  GENOTIPO + longitude +  Tmin_Maxima + 
    s(Tmin_ACC_V) + Tmin_ACC_R + s(Chuva_ACC_R) + s(Rad_ACC)	, family = gaussian, data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409","BR IRGA 412",	"BRS 7 TAIM",	"BRS A702 CL",	"BRS BIGUA",	"BRS FRONTEIRA",	"BRS JABURU",	"BRS JACANA",	"BRS PELOTA",	"BRS TROPICAL",	"BRSMG RUBELITA",	"DIAMANTE",	"EPAGRI 108",	"EPAGRI 109",	"IRGA 424 RI",	"IRGA 425",	"IRGA 428",	"IRGA 429",	"JEQUITIBA",	"PR306",	"PR349",	"PUITA INTA CL",	"RORAIMA",	"SC173",	"SC237",	"SC240",	"SC250",	"SCS 112",	"SCS 114 ANDOSAN",	"SCS 116 SATORU",	"SCS 121 CL",	"SCSBRS 111",	"SCSBRS PIRACEMA",	"URUCUI", "PR67", "IAC1289")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Norte_GAM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```
### ERRO
```{r}
GAM<- data.frame("Erro" = res_Norte_GAM, "Modelo" = "GAM")
LM<- data.frame("Erro" = res_Norte_LM, "Modelo" = "LM")


val<- data.frame()
val<- data.frame("Erro" = c(LM$Erro,GAM$Erro), "Modelo" = c(LM$Modelo,GAM$Modelo) )

v2<-ggplot(data = val, aes(y = Erro, x= Modelo, color=Modelo, fill = Modelo )) +
   geom_boxplot(
    width = .2, fill = "white",
    size = 1.5, outlier.shape = NA
  ) +
  ggdist::stat_halfeye(
    adjust = .60, 
    width = .55, 
    color = NA, 
    position = position_nudge(x = .14)
  ) +
  geom_point(
    position = position_nudge(x = -.22),
    shape = 95, size = 12, alpha = .25
  )+
  labs(y= "Average absolute error (days)", x="")+
  guides(color=FALSE)+
  scale_color_viridis_d()+
   scale_fill_viridis_d()+
   theme_classic(base_size = 12)+
 theme(legend.position="none")

```

## SUL

```{r}
Genotipos  <- Sul$GENOTIPO
SELECAO_GEN <- c("SAO FRANCISCO", "SCSBRS 111","CT8452","DIAMANTE","MOXOTO","EEA34","EPAGRI 109", "BRS JABURU","PR331")

Sul$GENOTIPO <- c(ifelse(Sul$GENOTIPO %in% SELECAO_GEN, 0 , Genotipos))

Sul <- Sul[Sul$GENOTIPO != 0,]
```


### LM
```{r}
res_Sul_LM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Sul$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Sul$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Sul[Sul$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Sul[Sul$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("AVAXI CL","BRS PAMPA",	"BRS PELOTA",	"EEA34",	"H7 CL",	"IRGA 417",	"JAVAE",	"PUITA INTA CL", "BRS A701 CL")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))



test = lm(FLO_M ~ GENOTIPO + Tmin_V + Tmin_ACC_V + Tmin_ACC_R + Chuva_ACC_R + 
    UR_V  , data = treinamento)



Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("AVAXI CL","BRS PAMPA",	"BRS PELOTA",	"EEA34",	"H7 CL",	"IRGA 417",	"JAVAE",	"PUITA INTA CL", "BRS A701 CL")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Sul_LM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```

### GAM
```{r}
res_Sul_GAM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Sul$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Sul$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Sul[Sul$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Sul[Sul$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c( "AVAXI CL", "BRS A701 CL", "BRS PAMPA", "BRS PELOTA","BRS PELOTA", "H7 CL", "IRGA 417","JAVAE","PUITA INTA CL","JEQUITIBA")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = gam(FLO_M ~  GENOTIPO + 	s(Tmax_Media )+ 	s(Tmin_V) + 	s(Tmin_ACC_V )+ 	s(Tmin_ACC_R) + 	s(UR_R)	, family = gaussian, data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c( "AVAXI CL", "BRS A701 CL", "BRS PAMPA", "BRS PELOTA","BRS PELOTA", "H7 CL", "IRGA 417","JAVAE","PUITA INTA CL","JEQUITIBA")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Sul_GAM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```
### ERRO
```{r}
GAM<- data.frame("Erro" = res_Sul_GAM, "Modelo" = "GAM")
LM<- data.frame("Erro" = res_Sul_LM, "Modelo" = "LM")


val<- data.frame()
val<- data.frame("Erro" = c(LM$Erro,GAM$Erro), "Modelo" = c(LM$Modelo,GAM$Modelo) )

v3<-ggplot(data = val, aes(y = Erro, x= Modelo, color=Modelo, fill = Modelo )) +
   geom_boxplot(
    width = .2, fill = "white",
    size = 1.5, outlier.shape = NA
  ) +
  ggdist::stat_halfeye(
    adjust = .60, 
    width = .55, 
    color = NA, 
    position = position_nudge(x = .14)
  ) +
  geom_point(
    position = position_nudge(x = -.22),
    shape = 95, size = 12, alpha = .25
  )+
  labs(y= "Average absolute error (days)", x="")+
  guides(color=FALSE)+
  scale_color_viridis_d()+
   scale_fill_viridis_d()+
   theme_classic(base_size = 12)+
 theme(legend.position="none")

```


## SUDESTE

```{r}
# Genótipos sem variabilidade removidos tanto do LM quanto do GAM
Genotipos  <- Sudeste$GENOTIPO
SELECAO_GEN <- c("ALIANCA","IRGA 428","BRS PAMPA","SCSBRS 113 TIO TAKA","PR498","BRS A702 CL","IRGA 425","PR67","IRGA 426","SC138","URUCUI","BRS SINUELO CL","IRGA 427","PR306")

Sudeste$GENOTIPO <- c(ifelse(Sudeste$GENOTIPO %in% SELECAO_GEN, 0 , Genotipos))

Sudeste <- Sudeste[Sudeste$GENOTIPO != 0,]
```

### LM

```{r}
res_Sudeste_LM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Sudeste$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Sudeste$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Sudeste[Sudeste$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Sudeste[Sudeste$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409","BRS 7 TAIM"	,"BRS A704"	,"BRS JACANA"	,"BRS QUERENCIA"	,"IAC1289"	,"IAPAR 58"	,"IRGA 417"	,"IRGA 422 CL"	,"IRGA 424"	,"JEQUITIBA"	,"PR349"	,"PR380"	,"SCS 112"	,"SCS 121 CL", "JAVAE","SCSBRS 111")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = lm(FLO_M ~ GENOTIPO + Tmin_Minima + Tmin_fld_m + Rad_ACC + Rad_ACC_V + 
    UR_fld_m, data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409","BRS 7 TAIM"	,"BRS A704"	,"BRS JACANA"	,"BRS QUERENCIA"	,"IAC1289"	,"IAPAR 58"	,"IRGA 417"	,"IRGA 422 CL"	,"IRGA 424"	,"JEQUITIBA"	,"PR349"	,"PR380"	,"SCS 112"	,"SCS 121 CL", "JAVAE","SCSBRS 111")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Sudeste_LM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```
### GAM
```{r}
res_Sudeste_GAM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Sudeste$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Sudeste$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Sudeste[Sudeste$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Sudeste[Sudeste$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("BRS ALVORADA","OUROMINAS", "BRS BIGUA", "METICA 1", "CICA 8", "BRS JABURU", "BRS GUARA", "BRS FORMOSO","BR IRGA 409","BRS 7 TAIM",	"BRS A704",	"BRS CATIANA",	"BRS JACANA",	"BRS PAMPEIRA",	"BRS QUERENCIA",	"BRS TROPICAL",	"IAC1289",	"IAPAR 58",	"IRGA 417",	"IRGA 424",	"JEQUITIBA",	"PR349",	"PR380",	"SC173",	"SC237",	"SC240",	"SC250",	"SCS 112",	"SCS 116 SATORU",	"SCS 121 CL",	"SCSBRS PIRACEMA")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

test = gam(FLO_M ~ GENOTIPO + s(Tmax_ACC_R) + s(Tmax_Minima) + s(Tmin_ACC_V), family = gaussian, data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("BRS ALVORADA","OUROMINAS", "BRS BIGUA", "METICA 1", "CICA 8", "BRS JABURU", "BRS GUARA", "BRS FORMOSO","BR IRGA 409","BRS 7 TAIM",	"BRS A704",	"BRS CATIANA",	"BRS JACANA",	"BRS PAMPEIRA",	"BRS QUERENCIA",	"BRS TROPICAL",	"IAC1289",	"IAPAR 58",	"IRGA 417",	"IRGA 424",	"JEQUITIBA",	"PR349",	"PR380",	"SC173",	"SC237",	"SC240",	"SC250",	"SCS 112",	"SCS 116 SATORU",	"SCS 121 CL",	"SCSBRS PIRACEMA")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Sudeste_GAM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```
### ERRO
```{r}
GAM<- data.frame("Erro" = res_Sudeste_GAM, "Modelo" = "GAM")
LM<- data.frame("Erro" = res_Sudeste_LM, "Modelo" = "LM")


val<- data.frame()
val<- data.frame("Erro" = c(LM$Erro,GAM$Erro), "Modelo" = c(LM$Modelo,GAM$Modelo) )

v4<-ggplot(data = val, aes(y = Erro, x= Modelo, color=Modelo, fill = Modelo )) +
   geom_boxplot(
    width = .2, fill = "white",
    size = 1.5, outlier.shape = NA
  ) +
  ggdist::stat_halfeye(
    adjust = .60, 
    width = .55, 
    color = NA, 
    position = position_nudge(x = .14)
  ) +
  geom_point(
    position = position_nudge(x = -.22),
    shape = 95, size = 12, alpha = .25
  )+
  labs(y= "Average absolute error (days)", x="")+
  guides(color=FALSE)+
  scale_color_viridis_d()+
   scale_fill_viridis_d()+
   theme_classic(base_size = 12)+
 theme(legend.position="none")
```
```{r}
((v1|v2|v3)/(v5|v4))+plot_annotation(tag_levels = 'A', tag_prefix = '(', tag_suffix = ')')
```


## NORDESTE

### LM
```{r}
res_Nordeste_LM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Nordeste$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Nordeste$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Nordeste[Nordeste$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Nordeste[Nordeste$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}

Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("BRS CATIANA", "OUROMINAS", "IAC1299", "PR267", "SCS 116 SATORU", "SCSBRS 113 TIO TAKA", "IAC1298", "SCS 121 CL", "BRS GUARA", "BRS FORMOSO", "EMPASC 101", "SCS 114 ANDOSAN", "ALIANCA","BRS A704",    "BRS JABURU",     "CICA 8",      "EPAGRI 108",    "EPAGRI 109",    "MOXOTO",    "PR268")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))



test = lm(log(FLO_M) ~ GENOTIPO + Altitude + Tmax_R + Tmax_Media + Tmax_V + 
    Tmax_ACC_V + Tmin_Maxima + Tmin_Minima + Tmin_V + Tmin_ACC_V + 
    Tmin_R + Tmin_ACC_R + Chuva_ACC + Chuva_ACC_V + Rad_ACC + 
    Rad_ACC_V + UR_R + Graus_dia_FLO, data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("BRS CATIANA", "OUROMINAS", "IAC1299", "PR267", "SCS 116 SATORU", "SCSBRS 113 TIO TAKA", "IAC1298", "SCS 121 CL", "BRS GUARA", "BRS FORMOSO", "EMPASC 101", "SCS 114 ANDOSAN", "ALIANCA","BRS A704",    "BRS JABURU",     "CICA 8",      "EPAGRI 108",    "EPAGRI 109",    "MOXOTO",    "PR268")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))



aux = predict(test,predicao)
aux

res_Nordeste_LM[i] = mean(abs(predicao$FLO_M - exp(aux)) )
print(i)
}
```
### GAM
```{r}
res_Nordeste_GAM<- NULL
for(i in 1:100) {

treinamento = NULL
predicao = NULL

nomesGenotipos = unique(Nordeste$GENOTIPO)

for (nomeGen in nomesGenotipos) {
  
  # Contando quantas vezes o genotipo aparece
  
  indexGen = which(Nordeste$GENOTIPO %in% nomeGen)
  
  # Verificando quantidade
  
  if (length(indexGen) <= 2) {
    
    # Adicionando informacao genotipo ao data.frame de trainemanto
    
    tempData = Nordeste[Nordeste$GENOTIPO == nomeGen, ]
    treinamento = rbind(treinamento, tempData)
    
    
  } else {
    
    # Genotipos que aparem mais de 3
    tempData = Nordeste[Nordeste$GENOTIPO == nomeGen, ]
    
    # Separando data.frame em treinamento e teste
    porcentagem = sample.split(tempData$GENOTIPO, SplitRatio = .70)
    
    # Treinamento
    treinamento = rbind(treinamento, subset(tempData, porcentagem == TRUE))
    
    # Predicao
    predicao = rbind(predicao, subset(tempData, porcentagem == FALSE))
    
  }

}
Genotipos  <- treinamento$GENOTIPO
SELECAO_GEN <- c("ALIANCA","BRS A704" , "BRS FORMOSO"   ,"CICA 8",   "EMPASC 101",   "EPAGRI 108",   "EPAGRI 109",   "MOXOTO",   "PR268",   "SCS 114 ANDOSAN", "BRS GUARA", "BRS JABURU", "BRSMG RUBELITA","SCS 116 SATORU","SCS 121 CL","SCSBRS 113 TIO TAKA", "BRS ALVORADA","BRS CATIANA","IAC1298","PR267", "IAC1299", "OUROMINAS")

treinamento$GENOTIPO <- c(ifelse(treinamento$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))


test = gam(FLO_M ~ GENOTIPO + Tmax_R + s(Tmax_ACC_R) + Tmax_V + Tmax_ACC_V + 
    s(Chuva_ACC_V), family = gaussian, data = treinamento)

Genotipos  <- predicao$GENOTIPO
SELECAO_GEN <- c("ALIANCA","BRS A704" , "BRS FORMOSO"   ,"CICA 8",   "EMPASC 101",   "EPAGRI 108",   "EPAGRI 109",   "MOXOTO",   "PR268",   "SCS 114 ANDOSAN", "BRS GUARA", "BRS JABURU", "BRSMG RUBELITA","SCS 116 SATORU","SCS 121 CL","SCSBRS 113 TIO TAKA", "BRS ALVORADA","BRS CATIANA","IAC1298","PR267", "IAC1299", "OUROMINAS")

predicao$GENOTIPO <- c(ifelse(predicao$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

aux = predict(test,predicao)
aux

res_Nordeste_GAM[i] = mean(abs(predicao$FLO_M - aux) )
print(i)
}
```
### ERRO

```{r}
GAM<- data.frame("Erro" = res_Nordeste_GAM, "Modelo" = "GAM")
LM<- data.frame("Erro" = res_Nordeste_LM, "Modelo" = "LM")


val<- data.frame()
val<- data.frame("Erro" = c(LM$Erro,GAM$Erro), "Modelo" = c(LM$Modelo,GAM$Modelo) )

v5<-ggplot(data = val, aes(y = Erro, x= Modelo, color=Modelo, fill = Modelo )) +
   geom_boxplot(
    width = .2, fill = "white",
    size = 1.5, outlier.shape = NA
  ) +
  ggdist::stat_halfeye(
    adjust = .60, 
    width = .55, 
    color = NA, 
    position = position_nudge(x = .14)
  ) +
  geom_point(
    position = position_nudge(x = -.22),
    shape = 95, size = 12, alpha = .25
  )+
  labs(y= "Average absolute error (days)", x="")+
  guides(color=FALSE)+
  scale_color_viridis_d()+
   scale_fill_viridis_d()+
   theme_classic(base_size = 12)+
 theme(legend.position="none")

```


# Figura 11

```{r}
((v1|v2|v3)/(v5|v4))+plot_annotation(tag_levels = 'A', tag_prefix = '(', tag_suffix = ')')
```






