---
title: "Figura 12"
author: "Gutemberg Resende Honorio Filho"
date: "07/01/2022"
output: html_document
---

# Pacotes

```{r}

if(!require(tidyverse)) install.packages("tidyverse")
if(!require(patchwork)) install.packages("patchwork")

#gam
if(!require(mgcv)) install.packages("mgcv")
```

# Dados 



```{r Diretório} 


# DIRETÓRIO DOS DADOS 

Tabelabruta<- read.csv("d:/Users/Cristiane Resende/Desktop/Gutemberg Honorio/Mestrado/Repositorio_4/Analise_e_modelagem_Arroz/Merge_1980_2018.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE) # tabela com os dados originais

# criando coluna com macrorregiões

Tabelabruta<- mutate(Tabelabruta,REGIAO = case_when(UF == 'GO'| UF == 'DF' |UF == 'MS' | UF == 'MT' ~ 'Centro-Oeste',
                              UF == 'AL'| UF == 'BA' |UF == 'CE' | UF == 'MA' | UF == 'PB' | UF == 'PE' | UF == 'PI' | UF == 'RN' | UF == 'SE' ~ 'Nordeste',
                              UF == 'AC' | UF == 'AM' | UF == 'AP' | UF == 'PA' | UF == 'RO' | UF == 'RR' | UF == 'TO' ~ 'Norte',
                              UF == 'ES' | UF == 'MG' | UF == 'SP' | UF == 'RJ' ~ 'Sudeste',
                              UF == 'RS' | UF == 'SC' | UF == 'PR' ~ 'Sul'))

# Tabelas acessório

TabelabrutaIRR = subset(Tabelabruta, SIST_CULT == "IRRIGATED") # Somente Irrigado
TabelabrutaTA = subset(Tabelabruta, SIST_CULT == "UPLAND") # Somente Terras altas

# Filtrando os dados


IRR<-TabelabrutaIRR %>% mutate(UR_Media=(umidade_Media),UR_V=	(umidade_V), UR_fld_m=	(umidade_fld_m),	UR_R=	(umidade_R), Graus_dia_ciclo=(graus_dia_ciclo), Graus_dia_FLO=(graus_dia_FLO+graus_dia_IP))

IRR <- select(IRR,latitude, longitude, GENOTIPO, ID_ENSAIO,ano, Altitude, REGIAO, UF, FLO_E, Tmax_Maxima ,Tmax_fld_m ,	Tmax_R,	Tmax_ACC_R, Tmax_Minima,	Tmax_Media,Tmax_V ,Tmax_ACC_V,	Tmin_Maxima,Tmin_Minima ,	Tmin_Media ,	Tmin_V ,	Tmin_ACC_V , Tmin_fld_m ,	Tmin_R,	Tmin_ACC_R , Chuva_ACC ,	Chuva_ACC_V, Chuva_ACC_R, Rad_ACC_R ,	Rad_ACC ,	Rad_ACC_V, UR_Media, UR_V, UR_fld_m,	UR_R, Graus_dia_ciclo, Graus_dia_FLO, ano)


#rm(TabelabrutaIRR,TabelabrutaTA,Tabelabruta)

# Removendo os genótipos que não serão estudados

IRR = IRR[IRR$GENOTIPO %in% c("ALIANCA",	"AVAXI CL",	"BR IRGA 409",	"BR IRGA 410",	"BR IRGA 412",	"BR IRGA 414",	"BRS 7 TAIM",	"BRS A701 CL",	"BRS A702 CL",	"BRS A704",	"BRS ALVORADA",	"BRS BIGUA",	"BRS CATIANA",	"BRS CIRAD 302",	"BRS FORMOSO",	"BRS FRONTEIRA",	"BRS GUARA",	"BRS JABURU",	"BRS JACANA",	"BRS PAMPA",	"BRS PAMPEIRA",	"BRS PELOTA",	"BRS QUERENCIA",	"BRS SINUELO CL",	"BRS TROPICAL",	"BRSMG RUBELITA",	"CICA 8",	"CT8452",	"DIAMANTE",	"EEA34",	"EMPASC 101",	"EMPASC 102",	"EPAGRI 108",	"EPAGRI 109",	"EPAGRI97-01",	"EPAGRI97-05",	"EPAGRI97-06",	"H6",	"H7 CL",	"IAC1289",	"IAC1298",	"IAC1299",	"IAC1307",	"IAC1311",	"IAPAR 58",	"IRGA 417",	"IRGA 422 CL",	"IRGA 424",	"IRGA 424 RI",	"IRGA 425",	"IRGA 426",	"IRGA 427",	"IRGA 428",	"IRGA 429",	"IRGA 430",	"IRGA97-05",	"IRGA97-10",	"IRGA97-11",	"IRGA97-28",	"JAVAE",	"JEQUITIBA",	"MARAJO",	"METICA 1",	"MOXOTO",	"OUROMINAS",	"PR267",	"PR268",	"PR306",	"PR331",	"PR349",	"PR380",	"PR498",	"PR631",	"PR67",	"PUITA INTA CL",	"RORAIMA",	"SAO FRANCISCO",	"SC138",	"SC173",	"SC237",	"SC240",	"SC250",	"SCS 112",	"SCS 114 ANDOSAN",	"SCS 116 SATORU",	"SCS 121 CL",	"SCSBRS 111",	"SCSBRS 113 TIO TAKA",	"SCSBRS PIRACEMA",	"SG11551",	"URUCUI"),]
IRR = IRR[IRR$UF!="MT",]

# Filtrando e gerando médias

IRR_Medio<- IRR %>% group_by(ID_ENSAIO, GENOTIPO, REGIAO) %>% summarise(  FLO_M= mean(FLO_E),  latitude= mean(latitude), longitude = mean(longitude), Altitude = mean(Altitude), Tmax_Maxima = mean(Tmax_Maxima) ,Tmax_fld_m = mean(Tmax_fld_m ),	Tmax_R= mean( Tmax_R),	Tmax_ACC_R= mean(Tmax_ACC_R ), Tmax_Minima= mean(Tmax_Minima ),	Tmax_Media= mean( Tmax_Media),Tmax_V = mean(Tmax_V ),Tmax_ACC_V= mean(Tmax_ACC_V ),	Tmin_Maxima= mean(Tmin_Maxima ),Tmin_Minima = mean(Tmin_Minima ),	Tmin_Media = mean(Tmin_Media ),	Tmin_V = mean(Tmin_V ),	Tmin_ACC_V = mean(Tmin_ACC_V ), Tmin_fld_m = mean( Tmin_fld_m),	Tmin_R= mean(Tmin_R ),	Tmin_ACC_R = mean(Tmin_ACC_R ), Chuva_ACC = mean(Chuva_ACC ),	Chuva_ACC_V= mean(Chuva_ACC_V ), Chuva_ACC_R= mean(Chuva_ACC_R ), Rad_ACC_R = mean(Rad_ACC_R ),	Rad_ACC = mean(Rad_ACC ),	Rad_ACC_V= mean(Rad_ACC_V ), UR_Media= mean( UR_Media), UR_V= mean( UR_V), UR_fld_m= mean(UR_fld_m ),	UR_R= mean(UR_R ), Graus_dia_ciclo= mean(Graus_dia_ciclo ), Graus_dia_FLO= mean(Graus_dia_FLO ))



# separando por macrorregião

Centro_oeste<- subset(IRR_Medio, (REGIAO == "Centro-Oeste")) # filtrando por região
Norte<- subset(IRR_Medio, (REGIAO == "Norte")) # filtrando por região
Nordeste<- subset(IRR_Medio, (REGIAO == "Nordeste")) # filtrando por região
Sul<- subset(IRR_Medio, (REGIAO == "Sul")) # filtrando por região
Sudeste<- subset(IRR_Medio, (REGIAO == "Sudeste")) # filtrando por região

```

# Resumo dos modelos

##Centro-oeste
###GAM
```{r}

Temporario <- Centro_oeste[,c(-1,-3)] # retirando as vaiáveis REGIAO e ID_ENSAIO
Temporario<- Temporario[c(-57, -60,-70,-116),]

Genotipos  <- Temporario$GENOTIPO
SELECAO_GEN <- c("BR IRGA 409" ,"BR IRGA 410"	,"BRS 7 TAIM"	,"BRS A701 CL"	,"BRS A702 CL"	,"BRS CIRAD 302"	,"BRS FRONTEIRA"	,"BRS JACANA"	,"BRS PELOTA"	,"BRS SINUELO CL"	,"EMPASC 102"	,"EPAGRI97-01"	,"EPAGRI97-05"	,"EPAGRI97-06"	,"IRGA 422 CL"	,"IRGA 424"	,"IRGA 424 RI"	,"IRGA 425"	,"IRGA 426"	,"IRGA97-11"	,"IRGA97-28"	,"JEQUITIBA"	,"PR306"	,"PR349"	,"PR498"	,"PR631"	,"SC240"	,"SC250", "IRGA 427","SCSBRS 111", "BRS PAMPA", "IAC1289", "PR67"
)

Temporario$GENOTIPO <- c(ifelse(Temporario$GENOTIPO %in% SELECAO_GEN, "AA" , Genotipos))

modelo_GAM_Centro_oeste = gam(FLO_M~GENOTIPO + s(Tmax_Minima) + Tmin_V + Tmin_ACC_V + 
    Tmin_R + s(Tmin_ACC_R) +  s(Rad_ACC) + 
    s(Graus_dia_FLO), family = gaussian, data = Temporario)
summary(modelo_GAM_Centro_oeste)
```

# Entrada
```{r}
#AA
Temporario1<- Temporario[Temporario$GENOTIPO %in% c("AA"),]
  media_Temporario1<- Temporario1 %>% group_by(GENOTIPO) %>% summarise(Tmin_V=mean(Tmin_V),   Tmin_ACC_V=mean(Tmin_ACC_V),  Tmin_R =mean(Tmin_R),    Tmax_Minima= mean(Tmax_Minima),   Tmin_ACC_R = mean(Tmin_ACC_R),  Rad_ACC=mean(Rad_ACC),   Graus_dia_FLO= mean(Graus_dia_FLO))
  
Tmin_V<-data.frame()
Tmin_V<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO", "Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_V["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmin_V["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_V["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_V["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_V["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_V["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_V["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_V)

Tmin_ACC_V<-data.frame()
Tmin_ACC_V<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_ACC_V["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_ACC_V["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_ACC_V["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_ACC_V["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_ACC_V["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_ACC_V["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_ACC_V["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_ACC_V)

Tmin_R<-data.frame()
Tmin_R<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_R["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmin_R["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_R["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_R["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmin_R["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_R["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_R["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_R)

Tmax_Minima<-data.frame()
Tmax_Minima<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmax_Minima["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmax_Minima["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmax_Minima["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmax_Minima["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Tmax_Minima["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmax_Minima["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmax_Minima["FLO"] = predict(modelo_GAM_Centro_oeste,Tmax_Minima)

Tmin_ACC_R<-data.frame()
Tmin_ACC_R<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Tmin_ACC_R["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Tmin_ACC_R["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Tmin_ACC_R["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Tmin_ACC_R["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Tmin_ACC_R["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Tmin_ACC_R["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Tmin_ACC_R["FLO"] = predict(modelo_GAM_Centro_oeste,Tmin_ACC_R)

Rad_ACC<-data.frame()
Rad_ACC<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Rad_ACC["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Rad_ACC["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Rad_ACC["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Rad_ACC["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Rad_ACC["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Rad_ACC["Graus_dia_FLO"]<- c(media_Temporario1$Graus_dia_FLO)
Rad_ACC["FLO"] = predict(modelo_GAM_Centro_oeste,Rad_ACC)

Graus_dia_FLO<-data.frame()
Graus_dia_FLO<- Temporario[Temporario$GENOTIPO %in% c("AA"),c("GENOTIPO","Tmin_V",   "Tmin_ACC_V",  "Tmin_R",    "Tmax_Minima",   "Tmin_ACC_R",  "Rad_ACC",   "Graus_dia_FLO")]
Graus_dia_FLO["Tmin_ACC_V"]<- c(media_Temporario1$Tmin_ACC_V)
Graus_dia_FLO["Tmin_V"]<- c(media_Temporario1$Tmin_V)
Graus_dia_FLO["Tmax_Minima"]<- c(media_Temporario1$Tmax_Minima)
Graus_dia_FLO["Tmin_ACC_R"]<- c(media_Temporario1$Tmin_ACC_R)
Graus_dia_FLO["Tmin_R"]<- c(media_Temporario1$Tmin_R)
Graus_dia_FLO["Rad_ACC"]<- c(media_Temporario1$Rad_ACC)
Graus_dia_FLO["FLO"] = predict(modelo_GAM_Centro_oeste,Graus_dia_FLO)

a=Tmin_V
b=Tmin_ACC_V
b=b[b$Tmin_ACC_V>= 850,]
c=Tmin_R
  c = c[c$Tmin_R<=23,]

d=Tmax_Minima
   d = d[d$Tmax_Minima>=22,]

e=Tmin_ACC_R
  e = e[e$Tmin_ACC_R>=550,]

f=Rad_ACC
  f = f[f$Rad_ACC<=3250,]

g=Graus_dia_FLO
  g = g[g$Graus_dia_FLO>=1350,]
  g = g[g$Graus_dia_FLO<=1900,]
  
#intercepto <- media_FLO
#a$crescimento = as.factor(ifelse(a$FLO > intercepto, yes = 1, no = 0))
#b$crescimento = as.factor(ifelse(b$FLO > intercepto, yes = 1, no = 0))
#c$crescimento = as.factor(ifelse(c$FLO > intercepto, yes = 1, no = 0))
#d$crescimento = as.factor(ifelse(d$FLO > intercepto, yes = 1, no = 0))
#e$crescimento = as.factor(ifelse(e$FLO > intercepto, yes = 1, no = 0))
#f$crescimento = as.factor(ifelse(f$FLO > intercepto, yes = 1, no = 0))
#g$crescimento = as.factor(ifelse(g$FLO > intercepto, yes = 1, no = 0))



test1<-ggplot(a, mapping = aes(x=Tmin_V, y=FLO) )+
    geom_point( col ="dodgerblue4")+
    scale_y_continuous(limits = c(78, 92))+
    #geom_point( mapping =aes(color = crescimento))+
    #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmin_V (ºC)" , y="Flowering (DAE)")+
  #guides(fill = FALSE) +
  #scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test2<-ggplot(b, mapping = aes(x=Tmin_ACC_V, y=FLO))+
  geom_point( col ="dodgerblue4")+
    scale_y_continuous(limits = c(78, 92))+
  #geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmin_ACC_V (ºC)" , y="Flowering (DAE)")+
  #guides(fill = FALSE) +
  #scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test3<-ggplot(c, mapping = aes(x= Tmin_R, y=FLO))+
  geom_point( col ="dodgerblue4")+
    scale_y_continuous(limits = c(78, 92))+
  #geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmin_R (ºC)" , y="Flowering (DAE)")+
  #guides(fill = FALSE) +
  #scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")


test4<-ggplot(d, mapping = aes(x=Tmax_Minima, y=FLO))+
  geom_point( col ="dodgerblue4")+
    scale_y_continuous(limits = c(78, 92))+
  #geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmax_Min (ºC)" , y="Flowering (DAE)")+
  #guides(fill = FALSE) +
  #scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test5<-ggplot(e, mapping = aes(x=Tmin_ACC_R, y=FLO))+
  geom_point( col ="dodgerblue4")+
    scale_y_continuous(limits = c(78, 92))+
  #geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Tmin_ACC_R (ºC)" , y="Flowering (DAE)")+
  #guides(fill = FALSE) +
  #scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test6<-ggplot(f, mapping = aes(x=Rad_ACC, y=FLO))+
  geom_point( col ="dodgerblue4")+
    scale_y_continuous(limits = c(78, 92))+
  #geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Rad_ACC (MJ/m²)" , y="Flowering (DAE)")+
  #guides(fill = FALSE) +
  #scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")

test7<-ggplot(g, mapping = aes(x=Graus_dia_FLO, y=FLO))+
  geom_point( col ="dodgerblue4")+
    scale_y_continuous(limits = c(78, 92))+
  #geom_point( mapping =aes(color = crescimento))+
  #geom_hline(yintercept = intercepto, alpha=0.8, linetype = 2)+
  labs(x= "Degree_days_FLO (ºC)" , y="Flowering (DAE)")+
  #guides(fill = FALSE) +
  #scale_color_manual(values = c("firebrick", "dodgerblue4"))+
  theme_classic()+
    theme(legend.position = "none")
```

#Figura 12
```{r}
((test6|test7|test1|test3)/(test5|test2|test4))+plot_annotation(tag_levels = 'A', tag_prefix = '(', tag_suffix = ')')


```
